import psycopg2

# try:
#     connection = psycopg2.connect(host='st-writer-rds.advinow-dev.int',
#                                          database='oe2',
#                                          user='root',
#                                          password='aQfeW4D3')
try:
    connection = psycopg2.connect(host='localhost',
                                         database='advi',
                                         user='postgres',
                                         password='BillGates94415')
    postgreSql_insert_query = """INSERT INTO template_symptomcategory (id, name, parent, category_id, bodypart_code, es_name, cascade_up, cascade_down) 
                           VALUES 
('1', 'Cheeks & Chin', 'PAIN_BODYPART02', 'PAIN_BODYPART25', 'BODYPART02', 'Mejillas y barbilla', NULL, NULL),
('2', 'Left Wrist', 'PAIN_BODYPART34', 'PAIN_BODYPART26', 'BODYPART12', 'Muñeca izquierda', NULL, NULL),
('3', 'Left Leg', 'PAIN_BODYPART01', 'PAIN_BODYPART27', 'BODYPART13', 'Pierna izquierda', NULL, NULL),
('4', 'Left Knee', 'PAIN_BODYPART27', 'PAIN_BODYPART28', 'BODYPART14', 'Rodilla izquierda', true, true),
('5', 'Left Elbow', 'PAIN_BODYPART34', 'PAIN_BODYPART29', 'BODYPART15', 'Codo izquierdo', true, true),
('6', 'Left Lower Arm', 'PAIN_BODYPART34', 'PAIN_BODYPART30', 'BODYPART16', 'Brazo izquierdo inferior', true, true),
('7', 'Left Upper Arm', 'PAIN_BODYPART34', 'PAIN_BODYPART31', 'BODYPART17', 'Brazo superior izquierdo', true, true),
('8', 'Left Lower Leg', 'PAIN_BODYPART27', 'PAIN_BODYPART32', 'BODYPART18', 'Pata inferior izquierda', true, true),
('9', 'Left Upper Leg', 'PAIN_BODYPART27', 'PAIN_BODYPART33', 'BODYPART19', 'Pata superior izquierda', true, true),
('10', 'Left Arm', 'PAIN_BODYPART01', 'PAIN_BODYPART34', 'BODYPART22', 'Brazo izquierdo', NULL, NULL),
('11', 'Left Ankle', 'PAIN_BODYPART27', 'PAIN_BODYPART35', 'BODYPART45', 'Tobillo izquierdo', true, true),
('12', 'Left Eye', 'PAIN_BODYPART02', 'PAIN_BODYPART36', 'BODYPART07', 'Ojo izquierdo', NULL, NULL),
('13', 'Left Ear', 'PAIN_BODYPART02', 'PAIN_BODYPART37', 'BODYPART08', 'Oreja izquierda', NULL, NULL),
('14', 'Right Temporal', 'PAIN_BODYPART02', 'PAIN_BODYPART38', 'BODYPART60', 'Derecho temporal', NULL, NULL),
('15', 'Left Temporal', 'PAIN_BODYPART02', 'PAIN_BODYPART39', 'BODYPART60', 'Temporal izquierdo', NULL, NULL),
('16', 'Back Head', 'PAIN_BODYPART02', 'PAIN_BODYPART40', 'BODYPART02', 'Cabeza trasera', true, true),
('17', 'Neck', 'PAIN_BODYPART02', 'PAIN_BODYPART41', 'BODYPART31', 'Cuello', NULL, NULL),
('18', 'Upper Lips', 'PAIN_BODYPART06', 'PAIN_BODYPART48', 'BODYPART27', 'Labios superiores', NULL, NULL),
('19', 'Lower Lips', 'PAIN_BODYPART06', 'PAIN_BODYPART49', 'BODYPART27', 'Labios inferiores', NULL, NULL),
('20', 'Upper Gums & Teeth', 'PAIN_BODYPART06', 'PAIN_BODYPART50', 'BODYPART29', 'Encías y dientes superiores', NULL, NULL),
('21', 'Lower Gums & Teeth', 'PAIN_BODYPART06', 'PAIN_BODYPART51', 'BODYPART29', 'Encías y dientes inferiores', NULL, NULL),
('22', 'Tongue', 'PAIN_BODYPART06', 'PAIN_BODYPART52', 'BODYPART26', 'Lengua', NULL, NULL),
('23', 'Roof Of Mouth', 'PAIN_BODYPART06', 'PAIN_BODYPART53', 'BODYPART34', 'Techo de la boca', NULL, NULL),
('24', 'Back of Throat', 'PAIN_BODYPART06', 'PAIN_BODYPART58', 'BODYPART35', 'Parte posterior de la garganta', NULL, NULL),
('25', 'Whole Body', '', 'SW_BODYPART01', 'BODYPART01', 'Todo el cuerpo', NULL, NULL),
('26', 'Head', 'SW_BODYPART01', 'SW_BODYPART02', 'BODYPART02', 'Cabeza', NULL, NULL),
('27', 'Nose', 'SW_BODYPART02', 'SW_BODYPART03', 'BODYPART03', 'Nariz', NULL, NULL),
('28', 'Throat', 'SW_BODYPART02', 'SW_BODYPART04', 'BODYPART04', 'Garganta', NULL, NULL),
('29', 'Chest', 'SW_BODYPART02', 'SW_BODYPART05', 'BODYPART05', 'Pecho', NULL, NULL),
('30', 'Mouth', 'SW_BODYPART02', 'SW_BODYPART06', 'BODYPART06', 'Boca', NULL, NULL),
('31', 'Right Eye', 'SW_BODYPART02', 'SW_BODYPART07', 'BODYPART07', 'Ojo derecho', NULL, NULL),
('32', 'Right Ear', 'SW_BODYPART02', 'SW_BODYPART08', 'BODYPART08', 'Oreja derecha', NULL, NULL),
('33', 'Forehead', 'SW_BODYPART02', 'SW_BODYPART09', 'BODYPART09', 'Frente', true, true),
('34', 'Pelvis', 'SW_BODYPART01', 'SW_BODYPART10', 'BODYPART10', 'Pelvis', NULL, NULL),
('35', 'Abdomen', 'SW_BODYPART01', 'SW_BODYPART11', 'BODYPART11', 'Abdomen', NULL, NULL),
('36', 'Right Wrist', 'SW_BODYPART22', 'SW_BODYPART12', 'BODYPART12', 'Muñeca derecha', NULL, NULL),
('37', 'Right Leg', 'SW_BODYPART01', 'SW_BODYPART13', 'BODYPART13', 'Pierna derecha', NULL, NULL),
('38', 'Right Knee', 'SW_BODYPART13', 'SW_BODYPART14', 'BODYPART14', 'Rodilla derecha', true, true),
('39', 'Right Elbow', 'SW_BODYPART22', 'SW_BODYPART15', 'BODYPART15', 'Codo derecho', true, true),
('40', 'Right Lower Arm', 'SW_BODYPART22', 'SW_BODYPART16', 'BODYPART16', 'Brazo inferior derecho', true, true),
('41', 'Right Upper Arm', 'SW_BODYPART22', 'SW_BODYPART17', 'BODYPART17', 'Brazo superior derecho', true, true),
('42', 'Right Lower Leg', 'SW_BODYPART13', 'SW_BODYPART18', 'BODYPART18', 'Pata inferior derecha', true, true),
('43', 'Right Upper Leg', 'SW_BODYPART13', 'SW_BODYPART19', 'BODYPART19', 'Pata superior derecha', true, true),
('44', 'Upper Back', 'SW_BODYPART01', 'SW_BODYPART20', 'BODYPART20', 'Superior de la espalda', NULL, NULL),
('45', 'Butt', 'SW_BODYPART01', 'SW_BODYPART21', 'BODYPART21', 'Extremo', NULL, NULL),
('46', 'Right Arm', 'SW_BODYPART01', 'SW_BODYPART22', 'BODYPART22', 'Brazo derecho', NULL, NULL),
('47', 'Right Ankle', 'SW_BODYPART13', 'SW_BODYPART23', 'BODYPART45', 'Tobillo derecho', NULL, NULL),
('48', 'Scalp', 'SW_BODYPART02', 'SW_BODYPART24', 'BODYPART57', 'Cuero cabelludo', true, true),
('49', 'Cheeks & Chin', 'SW_BODYPART02', 'SW_BODYPART25', 'BODYPART02', 'Mejillas y barbilla', NULL, NULL),
('50', 'Left Wrist', 'SW_BODYPART34', 'SW_BODYPART26', 'BODYPART12', 'Muñeca izquierda', NULL, NULL),
('51', 'Left Leg', 'SW_BODYPART01', 'SW_BODYPART27', 'BODYPART13', 'Pierna izquierda', NULL, NULL),
('52', 'Left Knee', 'SW_BODYPART27', 'SW_BODYPART28', 'BODYPART14', 'Rodilla izquierda', true, true),
('53', 'Left Elbow', 'SW_BODYPART34', 'SW_BODYPART29', 'BODYPART15', 'Codo izquierdo', true, true),
('54', 'Left Lower Arm', 'SW_BODYPART34', 'SW_BODYPART30', 'BODYPART16', 'Brazo izquierdo inferior', true, true),
('55', 'Left Upper Arm', 'SW_BODYPART34', 'SW_BODYPART31', 'BODYPART17', 'Brazo superior izquierdo', true, true),
('56', 'Left Lower Leg', 'SW_BODYPART27', 'SW_BODYPART32', 'BODYPART18', 'Pata inferior izquierda', true, true),
('57', 'Left Upper Leg', 'SW_BODYPART27', 'SW_BODYPART33', 'BODYPART19', 'Pata superior izquierda', true, true),
('58', 'Left Arm', 'SW_BODYPART01', 'SW_BODYPART34', 'BODYPART22', 'Brazo izquierdo', NULL, NULL),
('59', 'Left Ankle', 'SW_BODYPART27', 'SW_BODYPART35', 'BODYPART45', 'Tobillo izquierdo', true, true),
('60', 'Left Eye', 'SW_BODYPART02', 'SW_BODYPART36', 'BODYPART07', 'Ojo izquierdo', NULL, NULL),
('61', 'Left Ear', 'SW_BODYPART02', 'SW_BODYPART37', 'BODYPART08', 'Oreja izquierda', NULL, NULL),
('62', 'Right Temporal', 'SW_BODYPART02', 'SW_BODYPART38', 'BODYPART60', 'Right Temporal', NULL, NULL),
('63', 'Left Temporal', 'SW_BODYPART02', 'SW_BODYPART39', 'BODYPART60', 'Temporal izquierdo', NULL, NULL),
('64', 'Back Head', 'SW_BODYPART02', 'SW_BODYPART40', 'BODYPART02', 'Cabeza trasera', true, true),
('65', 'Neck', 'SW_BODYPART02', 'SW_BODYPART41', 'BODYPART31', 'Cuello', NULL, NULL),
('66', 'Upper Lips', 'SW_BODYPART06', 'SW_BODYPART48', 'BODYPART27', 'Labios superiores', NULL, NULL),
('67', 'Lower Lips', 'SW_BODYPART06', 'SW_BODYPART49', 'BODYPART27', 'Labios inferiores', NULL, NULL),
('68', 'Upper Gums & Teeth', 'SW_BODYPART06', 'SW_BODYPART50', 'BODYPART29', 'Encías y dientes superiores', NULL, NULL),
('69', 'Lower Gums & Teeth', 'SW_BODYPART06', 'SW_BODYPART51', 'BODYPART29', 'Encías y dientes inferiores', NULL, NULL),
('70', 'Tongue', 'SW_BODYPART06', 'SW_BODYPART52', 'BODYPART26', 'Lengua', NULL, NULL),
('71', 'Roof Of Mouth', 'SW_BODYPART06', 'SW_BODYPART53', 'BODYPART34', 'Techo de la boca', NULL, NULL),
('72', 'Back of Throat', 'SW_BODYPART06', 'SW_BODYPART58', 'BODYPART35', 'Parte posterior de la garganta', NULL, NULL),
('73', 'Core Symptoms', '', 'SYMPTCG01', '', 'Síntomas principales', NULL, NULL),
('74', 'Family History', '', 'SYMPTCG02', '', 'Historia familiar', NULL, NULL),
('75', 'Personal History', '', 'SYMPTCG03', '', 'Historia personal', NULL, NULL),
('76', 'Surgical History', '', 'SYMPTCG04', '', 'Historia Quirúrgica', NULL, NULL),
('77', 'Dietary', '', 'SYMPTCG05', '', 'Dietético', NULL, NULL),
('78', 'Environment', '', 'SYMPTCG06', '', 'Ambiente', NULL, NULL),
('79', 'Occupational Risk', '', 'SYMPTCG07', '', 'Riesgo Laboral', NULL, NULL),
('80', 'Sleeping Patterns', '', 'SYMPTCG09', '', 'Patrones de sueño', NULL, NULL),
('81', 'Other Factors', '', 'SYMPTCG10', '', 'Otros factores', NULL, NULL),
('82', 'Cognitive / Nervous System', '', 'SYMPTCG11', '', 'Sistema cognitivo / nervioso', NULL, NULL),
('83', 'Emotions', '', 'SYMPTCG12', '', 'Emociones', NULL, NULL),
('84', 'Psychological', '', 'SYMPTCG13', '', 'Psicológico', NULL, NULL),
('85', 'Core Symptoms', '', 'SYMPTCG14', '', 'Síntomas principales', NULL, NULL),
('86', 'Sexual', '', 'SYMPTCG15', '', 'Sexual', NULL, NULL),
('87', 'Whole Body', '', 'BODYPART01', '', 'Todo el cuerpo', NULL, NULL),
('88', 'Head', 'BODYPART01', 'BODYPART02', '', 'Cabeza', NULL, NULL),
('89', 'Nose', 'BODYPART02', 'BODYPART03', '', 'Nariz', NULL, NULL),
('90', 'Throat', 'BODYPART02', 'BODYPART04', '', 'Garganta', NULL, NULL),
('91', 'Mouth', 'BODYPART02', 'BODYPART06', '', 'Boca', NULL, NULL),
('92', 'Eyes', 'BODYPART02', 'BODYPART07', '', 'Ojos', NULL, NULL),
('93', 'Ears', 'BODYPART02', 'BODYPART08', '', 'Orejas', NULL, NULL),
('94', 'Forehead', 'BODYPART02', 'BODYPART09', '', 'Frente', NULL, NULL),
('95', 'Pelvis', 'BODYPART01', 'BODYPART10', '', 'Pelvis', NULL, NULL),
('96', 'Abdomen', 'BODYPART01', 'BODYPART11', '', 'Abdomen', NULL, NULL),
('97', 'Wrists', 'BODYPART22', 'BODYPART12', '', 'Muñecas', NULL, NULL),
('98', 'Legs', 'BODYPART01', 'BODYPART13', '', 'Piernas', NULL, NULL),
('99', 'Knee', 'BODYPART13', 'BODYPART14', '', 'Rodilla', NULL, NULL),
('100', 'Elbow', 'BODYPART22', 'BODYPART15', '', 'Codo', NULL, NULL),
('101', 'Lower Arm', 'BODYPART22', 'BODYPART16', '', 'Antebrazo', NULL, NULL),
('102', 'Upper Arm', 'BODYPART22', 'BODYPART17', '', 'Parte superior del brazo', NULL, NULL),
('103', 'Lower Leg', 'BODYPART13', 'BODYPART18', '', 'Pierna inferior', NULL, NULL),
('104', 'Upper Leg', 'BODYPART13', 'BODYPART19', '', 'Muslo', NULL, NULL),
('105', 'Upper Back', 'BODYPART01', 'BODYPART20', '', 'Superior de la espalda', NULL, NULL),
('106', 'Butt', 'BODYPART01', 'BODYPART21', '', 'Extremo', NULL, NULL),
('107', 'Arms', 'BODYPART01', 'BODYPART22', '', 'Brazos', NULL, NULL),
('108', 'Feet', 'BODYPART13', 'BODYPART23', '', 'Pies', NULL, NULL),
('109', 'Tongue', 'BODYPART06', 'BODYPART26', '', 'Lengua', NULL, NULL),
('110', 'Lips', 'BODYPART06', 'BODYPART27', '', 'Labios', NULL, NULL),
('111', 'Gums & Teeth', 'BODYPART06', 'BODYPART29', '', 'Gomas y dientes', NULL, NULL),
('112', 'Neck', 'BODYPART02', 'BODYPART31', '', 'Cuello', NULL, NULL),
('113', 'Roof Of Mouth', 'BODYPART06', 'BODYPART34', '', 'Techo de la boca', NULL, NULL),
('114', 'Back of Throat', 'BODYPART06', 'BODYPART35', '', 'Parte posterior de la garganta', NULL, NULL),
('115', 'Whole Body', '', 'PAIN_BODYPART01', 'BODYPART01', 'Todo el cuerpo', NULL, NULL),
('116', 'Head', 'PAIN_BODYPART01', 'PAIN_BODYPART02', 'BODYPART02', 'Cabeza', NULL, NULL),
('117', 'Nose', 'PAIN_BODYPART02', 'PAIN_BODYPART03', 'BODYPART03', 'Nariz', NULL, NULL),
('118', 'Throat', 'PAIN_BODYPART02', 'PAIN_BODYPART04', 'BODYPART04', 'Garganta', NULL, NULL),
('119', 'Chest', 'PAIN_BODYPART01', 'PAIN_BODYPART05', 'BODYPART05', 'Pecho', NULL, NULL),
('120', 'Mouth', 'PAIN_BODYPART02', 'PAIN_BODYPART06', 'BODYPART06', 'Boca', NULL, NULL),
('121', 'Right Eye', 'PAIN_BODYPART02', 'PAIN_BODYPART07', 'BODYPART07', 'Ojo derecho', NULL, NULL),
('122', 'Right Ear', 'PAIN_BODYPART02', 'PAIN_BODYPART08', 'BODYPART08', 'Oreja derecha', NULL, NULL),
('123', 'Forehead', 'PAIN_BODYPART02', 'PAIN_BODYPART09', 'BODYPART09', 'Frente', true, true),
('124', 'Pelvis', 'PAIN_BODYPART01', 'PAIN_BODYPART10', 'BODYPART10', 'Pelvis', NULL, NULL),
('125', 'Abdomen', 'PAIN_BODYPART01', 'PAIN_BODYPART11', 'BODYPART11', 'Abdomen', NULL, NULL),
('126', 'Right Wrist', 'PAIN_BODYPART22', 'PAIN_BODYPART12', 'BODYPART12', 'Muñeca derecha', NULL, NULL),
('127', 'Right Leg', 'PAIN_BODYPART01', 'PAIN_BODYPART13', 'BODYPART13', 'Pierna derecha', NULL, NULL),
('128', 'Right Knee', 'PAIN_BODYPART13', 'PAIN_BODYPART14', 'BODYPART14', 'Rodilla derecha', true, true),
('129', 'Right Elbow', 'PAIN_BODYPART22', 'PAIN_BODYPART15', 'BODYPART15', 'Codo derecho', true, true),
('130', 'Right Lower Arm', 'PAIN_BODYPART22', 'PAIN_BODYPART16', 'BODYPART16', 'Brazo inferior derecho', true, true),
('131', 'Right Upper Arm', 'PAIN_BODYPART22', 'PAIN_BODYPART17', 'BODYPART17', 'Brazo superior derecho', true, true),
('132', 'Right Lower Leg', 'PAIN_BODYPART13', 'PAIN_BODYPART18', 'BODYPART18', 'Pata inferior derecha', true, true),
('133', 'Right Upper Leg', 'PAIN_BODYPART13', 'PAIN_BODYPART19', 'BODYPART19', 'Pata superior derecha', true, true),
('134', 'Upper Back', 'PAIN_BODYPART01', 'PAIN_BODYPART20', 'BODYPART20', 'Superior de la espalda', NULL, NULL),
('135', 'Butt', 'PAIN_BODYPART01', 'PAIN_BODYPART21', 'BODYPART21', 'Extremo', NULL, NULL),
('136', 'Right Arm', 'PAIN_BODYPART01', 'PAIN_BODYPART22', 'BODYPART22', 'Brazo derecho', NULL, NULL),
('137', 'Right Ankle', 'PAIN_BODYPART13', 'PAIN_BODYPART23', 'BODYPART45', 'Tobillo derecho', true, true),
('138', 'Scalp', 'PAIN_BODYPART02', 'PAIN_BODYPART24', 'BODYPART57', 'Cuero cabelludo', true, true),
('139', 'Upper Left Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART59', 'BODYPART49', 'Abdomen superior izquierdo', true, true),
('140', 'Upper Center Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART60', 'BODYPART48', 'Abdomen central superior', true, true),
('141', 'Upper Right Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART61', 'BODYPART47', 'Abdomen superior derecho', true, true),
('142', 'Middle Left Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART62', 'BODYPART52', 'Abdomen medio izquierdo', true, true),
('143', 'Middle Center Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART63', 'BODYPART51', 'Centro Medio Abdomen', true, true),
('144', 'Middle Right Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART64', 'BODYPART50', 'Abdomen medio derecho', true, true),
('145', 'Lower Left Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART65', 'BODYPART55', 'Abdomen inferior izquierdo', true, true),
('146', 'Lower Center Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART66', 'BODYPART54', 'Abdomen central inferior', true, true),
('147', 'Lower Right Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART67', 'BODYPART53', 'Abdomen inferior derecho', true, true),
('148', 'Upper Left Abdomen', 'SW_BODYPART11', 'SW_BODYPART59', 'BODYPART49', 'Abdomen superior izquierdo', true, true),
('149', 'Upper Center Abdomen', 'SW_BODYPART11', 'SW_BODYPART60', 'BODYPART48', 'Abdomen central superior', true, true),
('150', 'Upper Right Abdomen', 'SW_BODYPART11', 'SW_BODYPART61', 'BODYPART47', 'Abdomen superior derecho', true, true),
('151', 'Middle Left Abdomen', 'SW_BODYPART11', 'SW_BODYPART62', 'BODYPART52', 'Abdomen medio izquierdo', true, true),
('152', 'Middle Center Abdomen', 'SW_BODYPART11', 'SW_BODYPART63', 'BODYPART51', 'Centro Medio Abdomen', true, true),
('153', 'Middle Right Abdomen', 'SW_BODYPART11', 'SW_BODYPART64', 'BODYPART50', 'Abdomen medio derecho', true, true),
('154', 'Lower Left Abdomen', 'SW_BODYPART11', 'SW_BODYPART65', 'BODYPART55', 'Abdomen inferior izquierdo', true, true),
('155', 'Lower Center Abdomen', 'SW_BODYPART11', 'SW_BODYPART66', 'BODYPART54', 'Abdomen central inferior', true, true),
('156', 'Lower Right Abdomen', 'SW_BODYPART11', 'SW_BODYPART67', 'BODYPART53', 'Abdomen inferior derecho', true, true),
('157', 'Ankles', 'BODYPART13', 'BODYPART45', '', 'Tobillos', NULL, NULL),
('158', 'Toes', 'BODYPART13', 'BODYPART46', '', 'Dedos de los pies', NULL, NULL),
('159', 'Right Hand', 'PAIN_BODYPART22', 'PAIN_BODYPART72', 'BODYPART36', 'Mano derecha', NULL, NULL),
('160', 'Right Thumb', 'PAIN_BODYPART22', 'PAIN_BODYPART73', 'BODYPART37', 'Pulgar derecho', NULL, NULL),
('161', 'Right Fingers', 'PAIN_BODYPART22', 'PAIN_BODYPART74', 'BODYPART38', 'Dedos derechos', NULL, NULL),
('162', 'Left Hand', 'PAIN_BODYPART34', 'PAIN_BODYPART75', 'BODYPART36', 'Mano izquierda', NULL, NULL),
('163', 'Left Thumb', 'PAIN_BODYPART34', 'PAIN_BODYPART76', 'BODYPART37', 'Pulgar izquierdo', NULL, NULL),
('164', 'Left Fingers', 'PAIN_BODYPART34', 'PAIN_BODYPART77', 'BODYPART38', 'Dedos izquierdos', NULL, NULL),
('165', 'Right Hand', 'SW_BODYPART22', 'SW_BODYPART72', 'BODYPART36', 'Mano derecha', NULL, NULL),
('166', 'Right Thumb', 'SW_BODYPART22', 'SW_BODYPART73', 'BODYPART37', 'Pulgar derecho', NULL, NULL),
('167', 'Right Fingers', 'SW_BODYPART22', 'SW_BODYPART74', 'BODYPART38', 'Dedos derechos', NULL, NULL),
('168', 'Left Hand', 'SW_BODYPART34', 'SW_BODYPART75', 'BODYPART36', 'Mano izquierda', NULL, NULL),
('169', 'Left Thumb', 'SW_BODYPART34', 'SW_BODYPART76', 'BODYPART37', 'Pulgar izquierdo', NULL, NULL),
('170', 'Left Fingers', 'SW_BODYPART34', 'SW_BODYPART77', 'BODYPART38', 'Dedos izquierdos', NULL, NULL),
('171', 'Hands', 'BODYPART22', 'BODYPART36', '', 'Manos', NULL, NULL),
('172', 'Thumbs', 'BODYPART22', 'BODYPART37', '', 'Pulgares', NULL, NULL),
('173', 'Fingers', 'BODYPART22', 'BODYPART38', '', 'Dedos', NULL, NULL),
('174', 'Lower Back', 'BODYPART01', 'BODYPART41', '', 'Espalda baja', NULL, NULL),
('175', 'Lower Back', 'PAIN_BODYPART01', 'PAIN_BODYPART78', 'BODYPART41', 'Espalda baja', NULL, NULL),
('176', 'Lower Back', 'SW_BODYPART01', 'SW_BODYPART78', 'BODYPART41', 'Espalda baja', NULL, NULL),
('177', 'Armpits', 'BODYPART05', 'BODYPART42', '', 'Axilas', NULL, NULL),
('178', 'Nipples', 'BODYPART05', 'BODYPART43', '', 'Pezones', NULL, NULL),
('179', 'Breasts', 'BODYPART05', 'BODYPART44', '', 'Pechos', NULL, NULL),
('180', 'Right Armpit', 'PAIN_BODYPART05', 'PAIN_BODYPART79', 'BODYPART42', 'Axila derecha', NULL, NULL),
('181', 'Left Armpit', 'PAIN_BODYPART05', 'PAIN_BODYPART80', 'BODYPART42', 'Axila izquierda', NULL, NULL),
('182', 'Right Armpit', 'SW_BODYPART05', 'SW_BODYPART79', 'BODYPART42', 'Axila derecha', NULL, NULL),
('183', 'Left Armpit', 'SW_BODYPART05', 'SW_BODYPART80', 'BODYPART42', 'Axila izquierda', NULL, NULL),
('184', 'Right Foot', 'PAIN_BODYPART13', 'PAIN_BODYPART91', 'BODYPART23', 'Pie derecho', NULL, NULL),
('185', 'Right Toes', 'PAIN_BODYPART13', 'PAIN_BODYPART92', 'BODYPART46', 'Derechas', NULL, NULL),
('186', 'Left Foot', 'PAIN_BODYPART27', 'PAIN_BODYPART93', 'BODYPART23', 'Pie izquierdo', NULL, NULL),
('187', 'Left Toes', 'PAIN_BODYPART27', 'PAIN_BODYPART94', 'BODYPART46', 'Dedos del pie izquierdo', NULL, NULL),
('188', 'Right Foot', 'SW_BODYPART13', 'SW_BODYPART91', 'BODYPART23', 'Pie derecho', NULL, NULL),
('189', 'Right Toes', 'SW_BODYPART13', 'SW_BODYPART92', 'BODYPART46', 'Derechas', NULL, NULL),
('190', 'Left Foot', 'SW_BODYPART27', 'SW_BODYPART93', 'BODYPART23', 'Pie izquierdo', NULL, NULL),
('191', 'Left Toes', 'SW_BODYPART27', 'SW_BODYPART94', 'BODYPART46', 'Dedos del pie izquierdo', NULL, NULL),
('192', 'Upper Right Abdomen', 'BODYPART11', 'BODYPART47', '', 'Abdomen superior derecho', NULL, NULL),
('193', 'Upper Center Abdomen', 'BODYPART11', 'BODYPART48', '', 'Abdomen central superior', NULL, NULL),
('194', 'Upper Left Abdomen', 'BODYPART11', 'BODYPART49', '', 'Abdomen superior izquierdo', NULL, NULL),
('195', 'Middle Right Abdomen', 'BODYPART11', 'BODYPART50', '', 'Abdomen medio derecho', NULL, NULL),
('196', 'Middle Center Abdomen', 'BODYPART11', 'BODYPART51', '', 'Centro Medio Abdomen', NULL, NULL),
('197', 'Middle Left Abdomen', 'BODYPART11', 'BODYPART52', '', 'Abdomen medio izquierdo', NULL, NULL),
('198', 'Lower Right Abdomen', 'BODYPART11', 'BODYPART53', '', 'Abdomen inferior derecho', NULL, NULL),
('199', 'Lower Center Abdomen', 'BODYPART11', 'BODYPART54', '', 'Abdomen central inferior', NULL, NULL),
('200', 'Lower Left Abdomen', 'BODYPART11', 'BODYPART55', '', 'Abdomen inferior izquierdo', NULL, NULL),
('201', 'Back Head', 'BODYPART02', 'BODYPART56', '', 'Cabeza trasera', NULL, NULL),
('202', 'Scalp', 'BODYPART02', 'BODYPART57', '', 'Cuero cabelludo', NULL, NULL),
('203', 'Metabolic Panel', '', 'SYMPTCG16', '', 'Panel metabólico', NULL, NULL),
('204', 'Urinalysis', '', 'SYMPTCG17', '', 'Análisis de orina', NULL, NULL),
('205', 'Lipids', '', 'SYMPTCG18', '', 'Lípidos', NULL, NULL),
('206', 'CBC', '', 'SYMPTCG19', '', 'CBC', NULL, NULL),
('207', 'Other', '', 'SYMPTCG20', '', 'Otro', NULL, NULL),
('208', 'CSF', '', 'SYMPTCG21', '', 'CSF', NULL, NULL),
('209', 'Shoulders', 'BODYPART22', 'BODYPART58', '', 'Espalda', NULL, NULL),
('210', 'Fetal/Neonatal Observations', '', 'SYMPTCG22', '', 'Observaciones fetales', NULL, NULL),
('211', 'Imaging', '', 'SYMPTCG23', '', 'Imágenes', NULL, NULL),
('212', 'Right Shoulder', 'PAIN_BODYPART17', 'PAIN_BODYPART95', 'BODYPART58', '', NULL, NULL),
('213', 'Left Shoulder', 'PAIN_BODYPART31', 'PAIN_BODYPART96', 'BODYPART58', '', NULL, NULL),
('214', 'Right Hip', 'PAIN_BODYPART13', 'PAIN_BODYPART97', 'BODYPART59', '', NULL, NULL),
('215', 'Left Hip', 'PAIN_BODYPART27', 'PAIN_BODYPART98', 'BODYPART59', '', NULL, NULL),
('216', 'Right Shoulder', 'SW_BODYPART17', 'SW_BODYPART95', 'BODYPART58', 'Hombro derecho', NULL, NULL),
('217', 'Left Shoulder', 'SW_BODYPART31', 'SW_BODYPART96', 'BODYPART58', 'Hombro izquierdo', NULL, NULL),
('218', 'Right Hip', 'SW_BODYPART13', 'SW_BODYPART97', 'BODYPART59', 'Cadera derecha', NULL, NULL),
('219', 'Left Hip', 'SW_BODYPART27', 'SW_BODYPART98', 'BODYPART59', 'Cadera izquierda', NULL, NULL),
('220', 'Hip', 'BODYPART13', 'BODYPART59', '', 'Caderas', NULL, NULL),
('221', 'Physical Exam', '', 'SYMPTCG24', '', 'Examen físico', NULL, NULL),
('222', 'Stool', '', 'SYMPTCG25', '', 'Taburete', NULL, NULL),
('223', 'Screenings', '', 'SYMPTCG26', '', 'Psicológico', NULL, NULL),
('224', 'PTSD', '', 'SYMPTCG27', '', 'PTSD', NULL, NULL),
('225', 'Core Symptoms', '', 'SYMPTCG28', '', 'Síntomas principales', NULL, NULL),
('226', 'Pathology', '', 'SYMPTCG29', '', 'Patología', NULL, NULL),
('227', 'Temporals', 'BODYPART02', 'BODYPART60', '', 'Temporals', NULL, NULL),
('228', 'Microbiology', '', 'SYMPTCG30', '', 'Microbiología', NULL, NULL),
('229', 'Tumor Markers', '', 'SYMPTCG31', '', 'Marcadores tumorales', NULL, NULL),
('230', 'Arterial Blood Gas', '', 'SYMPTCG32', '', 'Gasometría Arterial', NULL, NULL),
('231', 'Core Symptoms', '', 'SYMPTCG33', '', 'Síntomas principales', NULL, NULL),
('232', 'Eyelids', 'SW_BODYPART07', 'SW_BODYPART101', 'BODYPART61', '', NULL, NULL),
('233', 'Chest', 'BODYPART01', 'BODYPART05', '', 'Cofre', NULL, NULL),
('234', 'Eyelids', 'BODYPART07', 'BODYPART61', '', '', NULL, NULL),
('235', 'Breasts', 'PAIN_BODYPART05', 'PAIN_BODYPART99', 'BODYPART44', '', NULL, true),
('236', 'Nipples', 'PAIN_BODYPART05', 'PAIN_BODYPART100', 'BODYPART43', '', NULL, true),
('237', 'Eyelids', 'PAIN_BODYPART07', 'PAIN_BODYPART101', 'BODYPART61', '', NULL, NULL),
('238', 'Breasts', 'SW_BODYPART05', 'SW_BODYPART99', 'BODYPART44', '', NULL, true),
('239', 'Nipples', 'SW_BODYPART05', 'SW_BODYPART100', 'BODYPART43', '', NULL, true),
('240', 'Assessment/Evaluation', '', 'SYMPTCG34', '', 'Valoración / Evaluación', NULL, NULL),
('241', 'Core Symptoms', '', 'SYMPTCG35', '', 'Síntomas principales', NULL, NULL)"""
    cursor = connection.cursor()
    cursor.execute(postgreSql_insert_query)
    connection.commit()
    print(cursor.rowcount, "Record inserted successfully into SymptomCategory table")
    cursor.close()
except psycopg2.OperationalError as error:
    print("Failed to insert record into SnomedCode table {}".format(error))