import psycopg2

try:
    connection = psycopg2.connect(host='st-writer-rds.advinow-dev.int',
                                         database='oe2',
                                         user='root',
                                         password='aQfeW4D3')
# try:
#     connection = psycopg2.connect(host='localhost',
#                                          database='dun',
#                                          user='postgres',
#                                          password='BillGates94415')
    postgreSql_insert_query = """INSERT INTO template_symptomcategory (id, name, parent, code, bodypart_code, es_name, cascade_up, cascade_down, symptom_template) 
                           VALUES 
('1', 'Cheeks & Chin', 'PAIN_BODYPART02', 'PAIN_BODYPART25', 'BODYPART02', 'Mejillas y barbilla', NULL, NULL, '{1,2,3}'),
('2', 'Left Wrist', 'PAIN_BODYPART34', 'PAIN_BODYPART26', 'BODYPART12', 'Muñeca izquierda', NULL, NULL, '{1,2,3}'),
('3', 'Left Leg', 'PAIN_BODYPART01', 'PAIN_BODYPART27', 'BODYPART13', 'Pierna izquierda', NULL, NULL, '{1,2,3}'),
('4', 'Left Knee', 'PAIN_BODYPART27', 'PAIN_BODYPART28', 'BODYPART14', 'Rodilla izquierda', true, true, '{1,2,3}'),
('5', 'Left Elbow', 'PAIN_BODYPART34', 'PAIN_BODYPART29', 'BODYPART15', 'Codo izquierdo', true, true, '{1,2,3}'),
('6', 'Left Lower Arm', 'PAIN_BODYPART34', 'PAIN_BODYPART30', 'BODYPART16', 'Brazo izquierdo inferior', true, true, '{1,2,3}'),
('7', 'Left Upper Arm', 'PAIN_BODYPART34', 'PAIN_BODYPART31', 'BODYPART17', 'Brazo superior izquierdo', true, true, '{1,2,3}'),
('8', 'Left Lower Leg', 'PAIN_BODYPART27', 'PAIN_BODYPART32', 'BODYPART18', 'Pata inferior izquierda', true, true, '{1,2,3}'),
('9', 'Left Upper Leg', 'PAIN_BODYPART27', 'PAIN_BODYPART33', 'BODYPART19', 'Pata superior izquierda', true, true, '{1,2,3}'),
('10', 'Left Arm', 'PAIN_BODYPART01', 'PAIN_BODYPART34', 'BODYPART22', 'Brazo izquierdo', NULL, NULL, '{1,2,3}'),
('11', 'Left Ankle', 'PAIN_BODYPART27', 'PAIN_BODYPART35', 'BODYPART45', 'Tobillo izquierdo', true, true, '{1,2,3}'),
('12', 'Left Eye', 'PAIN_BODYPART02', 'PAIN_BODYPART36', 'BODYPART07', 'Ojo izquierdo', NULL, NULL, '{1,2,3}'),
('13', 'Left Ear', 'PAIN_BODYPART02', 'PAIN_BODYPART37', 'BODYPART08', 'Oreja izquierda', NULL, NULL, '{1,2,3}'),
('14', 'Right Temporal', 'PAIN_BODYPART02', 'PAIN_BODYPART38', 'BODYPART60', 'Derecho temporal', NULL, NULL, '{1,2,3}'),
('15', 'Left Temporal', 'PAIN_BODYPART02', 'PAIN_BODYPART39', 'BODYPART60', 'Temporal izquierdo', NULL, NULL, '{1,2,3}'),
('16', 'Back Head', 'PAIN_BODYPART02', 'PAIN_BODYPART40', 'BODYPART02', 'Cabeza trasera', true, true, '{1,2,3}'),
('17', 'Neck', 'PAIN_BODYPART02', 'PAIN_BODYPART41', 'BODYPART31', 'Cuello', NULL, NULL, '{1,2,3}'),
('18', 'Upper Lips', 'PAIN_BODYPART06', 'PAIN_BODYPART48', 'BODYPART27', 'Labios superiores', NULL, NULL, '{1,2,3}'),
('19', 'Lower Lips', 'PAIN_BODYPART06', 'PAIN_BODYPART49', 'BODYPART27', 'Labios inferiores', NULL, NULL, '{1,2,3}'),
('20', 'Upper Gums & Teeth', 'PAIN_BODYPART06', 'PAIN_BODYPART50', 'BODYPART29', 'Encías y dientes superiores', NULL, NULL, '{1,2,3}'),
('21', 'Lower Gums & Teeth', 'PAIN_BODYPART06', 'PAIN_BODYPART51', 'BODYPART29', 'Encías y dientes inferiores', NULL, NULL, '{1,2,3}'),
('22', 'Tongue', 'PAIN_BODYPART06', 'PAIN_BODYPART52', 'BODYPART26', 'Lengua', NULL, NULL, '{1,2,3}'),
('23', 'Roof Of Mouth', 'PAIN_BODYPART06', 'PAIN_BODYPART53', 'BODYPART34', 'Techo de la boca', NULL, NULL, '{1,2,3}'),
('24', 'Back of Throat', 'PAIN_BODYPART06', 'PAIN_BODYPART58', 'BODYPART35', 'Parte posterior de la garganta', NULL, NULL, '{1,2,3}'),
('25', 'Whole Body', '', 'SW_BODYPART01', 'BODYPART01', 'Todo el cuerpo', NULL, NULL, '{1,2,3}'),
('26', 'Head', 'SW_BODYPART01', 'SW_BODYPART02', 'BODYPART02', 'Cabeza', NULL, NULL, '{1,2,3}'),
('27', 'Nose', 'SW_BODYPART02', 'SW_BODYPART03', 'BODYPART03', 'Nariz', NULL, NULL, '{1,2,3}'),
('28', 'Throat', 'SW_BODYPART02', 'SW_BODYPART04', 'BODYPART04', 'Garganta', NULL, NULL, '{1,2,3}'),
('29', 'Chest', 'SW_BODYPART02', 'SW_BODYPART05', 'BODYPART05', 'Pecho', NULL, NULL, '{1,2,3}'),
('30', 'Mouth', 'SW_BODYPART02', 'SW_BODYPART06', 'BODYPART06', 'Boca', NULL, NULL, '{1,2,3}'),
('31', 'Right Eye', 'SW_BODYPART02', 'SW_BODYPART07', 'BODYPART07', 'Ojo derecho', NULL, NULL, '{1,2,3}'),
('32', 'Right Ear', 'SW_BODYPART02', 'SW_BODYPART08', 'BODYPART08', 'Oreja derecha', NULL, NULL, '{1,2,3}'),
('33', 'Forehead', 'SW_BODYPART02', 'SW_BODYPART09', 'BODYPART09', 'Frente', true, true, '{1,2,3}'),
('34', 'Pelvis', 'SW_BODYPART01', 'SW_BODYPART10', 'BODYPART10', 'Pelvis', NULL, NULL, '{1,2,3}'),
('35', 'Abdomen', 'SW_BODYPART01', 'SW_BODYPART11', 'BODYPART11', 'Abdomen', NULL, NULL, '{1,2,3}'),
('36', 'Right Wrist', 'SW_BODYPART22', 'SW_BODYPART12', 'BODYPART12', 'Muñeca derecha', NULL, NULL, '{1,2,3}'),
('37', 'Right Leg', 'SW_BODYPART01', 'SW_BODYPART13', 'BODYPART13', 'Pierna derecha', NULL, NULL, '{1,2,3}'),
('38', 'Right Knee', 'SW_BODYPART13', 'SW_BODYPART14', 'BODYPART14', 'Rodilla derecha', true, true, '{1,2,3}'),
('39', 'Right Elbow', 'SW_BODYPART22', 'SW_BODYPART15', 'BODYPART15', 'Codo derecho', true, true, '{1,2,3}'),
('40', 'Right Lower Arm', 'SW_BODYPART22', 'SW_BODYPART16', 'BODYPART16', 'Brazo inferior derecho', true, true, '{1,2,3}'),
('41', 'Right Upper Arm', 'SW_BODYPART22', 'SW_BODYPART17', 'BODYPART17', 'Brazo superior derecho', true, true, '{1,2,3}'),
('42', 'Right Lower Leg', 'SW_BODYPART13', 'SW_BODYPART18', 'BODYPART18', 'Pata inferior derecha', true, true, '{1,2,3}'),
('43', 'Right Upper Leg', 'SW_BODYPART13', 'SW_BODYPART19', 'BODYPART19', 'Pata superior derecha', true, true, '{1,2,3}'),
('44', 'Upper Back', 'SW_BODYPART01', 'SW_BODYPART20', 'BODYPART20', 'Superior de la espalda', NULL, NULL, '{1,2,3}'),
('45', 'Butt', 'SW_BODYPART01', 'SW_BODYPART21', 'BODYPART21', 'Extremo', NULL, NULL, '{1,2,3}'),
('46', 'Right Arm', 'SW_BODYPART01', 'SW_BODYPART22', 'BODYPART22', 'Brazo derecho', NULL, NULL, '{1,2,3}'),
('47', 'Right Ankle', 'SW_BODYPART13', 'SW_BODYPART23', 'BODYPART45', 'Tobillo derecho', NULL, NULL, '{1,2,3}'),
('48', 'Scalp', 'SW_BODYPART02', 'SW_BODYPART24', 'BODYPART57', 'Cuero cabelludo', true, true, '{1,2,3}'),
('49', 'Cheeks & Chin', 'SW_BODYPART02', 'SW_BODYPART25', 'BODYPART02', 'Mejillas y barbilla', NULL, NULL, '{1,2,3}'),
('50', 'Left Wrist', 'SW_BODYPART34', 'SW_BODYPART26', 'BODYPART12', 'Muñeca izquierda', NULL, NULL, '{1,2,3}'),
('51', 'Left Leg', 'SW_BODYPART01', 'SW_BODYPART27', 'BODYPART13', 'Pierna izquierda', NULL, NULL, '{1,2,3}'),
('52', 'Left Knee', 'SW_BODYPART27', 'SW_BODYPART28', 'BODYPART14', 'Rodilla izquierda', true, true, '{1,2,3}'),
('53', 'Left Elbow', 'SW_BODYPART34', 'SW_BODYPART29', 'BODYPART15', 'Codo izquierdo', true, true, '{1,2,3}'),
('54', 'Left Lower Arm', 'SW_BODYPART34', 'SW_BODYPART30', 'BODYPART16', 'Brazo izquierdo inferior', true, true, '{1,2,3}'),
('55', 'Left Upper Arm', 'SW_BODYPART34', 'SW_BODYPART31', 'BODYPART17', 'Brazo superior izquierdo', true, true, '{1,2,3}'),
('56', 'Left Lower Leg', 'SW_BODYPART27', 'SW_BODYPART32', 'BODYPART18', 'Pata inferior izquierda', true, true, '{1,2,3}'),
('57', 'Left Upper Leg', 'SW_BODYPART27', 'SW_BODYPART33', 'BODYPART19', 'Pata superior izquierda', true, true, '{1,2,3}'),
('58', 'Left Arm', 'SW_BODYPART01', 'SW_BODYPART34', 'BODYPART22', 'Brazo izquierdo', NULL, NULL, '{1,2,3}'),
('59', 'Left Ankle', 'SW_BODYPART27', 'SW_BODYPART35', 'BODYPART45', 'Tobillo izquierdo', true, true, '{1,2,3}'),
('60', 'Left Eye', 'SW_BODYPART02', 'SW_BODYPART36', 'BODYPART07', 'Ojo izquierdo', NULL, NULL, '{1,2,3}'),
('61', 'Left Ear', 'SW_BODYPART02', 'SW_BODYPART37', 'BODYPART08', 'Oreja izquierda', NULL, NULL, '{1,2,3}'),
('62', 'Right Temporal', 'SW_BODYPART02', 'SW_BODYPART38', 'BODYPART60', 'Right Temporal', NULL, NULL, '{1,2,3}'),
('63', 'Left Temporal', 'SW_BODYPART02', 'SW_BODYPART39', 'BODYPART60', 'Temporal izquierdo', NULL, NULL, '{1,2,3}'),
('64', 'Back Head', 'SW_BODYPART02', 'SW_BODYPART40', 'BODYPART02', 'Cabeza trasera', true, true, '{1,2,3}'),
('65', 'Neck', 'SW_BODYPART02', 'SW_BODYPART41', 'BODYPART31', 'Cuello', NULL, NULL, '{1,2,3}'),
('66', 'Upper Lips', 'SW_BODYPART06', 'SW_BODYPART48', 'BODYPART27', 'Labios superiores', NULL, NULL, '{1,2,3}'),
('67', 'Lower Lips', 'SW_BODYPART06', 'SW_BODYPART49', 'BODYPART27', 'Labios inferiores', NULL, NULL, '{1,2,3}'),
('68', 'Upper Gums & Teeth', 'SW_BODYPART06', 'SW_BODYPART50', 'BODYPART29', 'Encías y dientes superiores', NULL, NULL, '{1,2,3}'),
('69', 'Lower Gums & Teeth', 'SW_BODYPART06', 'SW_BODYPART51', 'BODYPART29', 'Encías y dientes inferiores', NULL, NULL, '{1,2,3}'),
('70', 'Tongue', 'SW_BODYPART06', 'SW_BODYPART52', 'BODYPART26', 'Lengua', NULL, NULL, '{1,2,3}'),
('71', 'Roof Of Mouth', 'SW_BODYPART06', 'SW_BODYPART53', 'BODYPART34', 'Techo de la boca', NULL, NULL, '{1,2,3}'),
('72', 'Back of Throat', 'SW_BODYPART06', 'SW_BODYPART58', 'BODYPART35', 'Parte posterior de la garganta', NULL, NULL, '{1,2,3}'),
('73', 'Core Symptoms', '', 'SYMPTCG01', '', 'Síntomas principales', NULL, NULL, '{1,2,3}'),
('74', 'Family History', '', 'SYMPTCG02', '', 'Historia familiar', NULL, NULL, '{1,2,3}'),
('75', 'Personal History', '', 'SYMPTCG03', '', 'Historia personal', NULL, NULL, '{1,2,3}'),
('76', 'Surgical History', '', 'SYMPTCG04', '', 'Historia Quirúrgica', NULL, NULL, '{1,2,3}'),
('77', 'Dietary', '', 'SYMPTCG05', '', 'Dietético', NULL, NULL, '{1,2,3}'),
('78', 'Environment', '', 'SYMPTCG06', '', 'Ambiente', NULL, NULL, '{1,2,3}'),
('79', 'Occupational Risk', '', 'SYMPTCG07', '', 'Riesgo Laboral', NULL, NULL, '{1,2,3}'),
('80', 'Sleeping Patterns', '', 'SYMPTCG09', '', 'Patrones de sueño', NULL, NULL, '{1,2,3}'),
('81', 'Other Factors', '', 'SYMPTCG10', '', 'Otros factores', NULL, NULL, '{1,2,3}'),
('82', 'Cognitive / Nervous System', '', 'SYMPTCG11', '', 'Sistema cognitivo / nervioso', NULL, NULL, '{1,2,3}'),
('83', 'Emotions', '', 'SYMPTCG12', '', 'Emociones', NULL, NULL, '{1,2,3}'),
('84', 'Psychological', '', 'SYMPTCG13', '', 'Psicológico', NULL, NULL, '{1,2,3}'),
('85', 'Core Symptoms', '', 'SYMPTCG14', '', 'Síntomas principales', NULL, NULL, '{1,2,3}'),
('86', 'Sexual', '', 'SYMPTCG15', '', 'Sexual', NULL, NULL, '{1,2,3}'),
('87', 'Whole Body', '', 'BODYPART01', '', 'Todo el cuerpo', NULL, NULL, '{1,2,3}'),
('88', 'Head', 'BODYPART01', 'BODYPART02', '', 'Cabeza', NULL, NULL, '{1,2,3}'),
('89', 'Nose', 'BODYPART02', 'BODYPART03', '', 'Nariz', NULL, NULL, '{1,2,3}'),
('90', 'Throat', 'BODYPART02', 'BODYPART04', '', 'Garganta', NULL, NULL, '{1,2,3}'),
('91', 'Mouth', 'BODYPART02', 'BODYPART06', '', 'Boca', NULL, NULL, '{1,2,3}'),
('92', 'Eyes', 'BODYPART02', 'BODYPART07', '', 'Ojos', NULL, NULL, '{1,2,3}'),
('93', 'Ears', 'BODYPART02', 'BODYPART08', '', 'Orejas', NULL, NULL, '{1,2,3}'),
('94', 'Forehead', 'BODYPART02', 'BODYPART09', '', 'Frente', NULL, NULL, '{1,2,3}'),
('95', 'Pelvis', 'BODYPART01', 'BODYPART10', '', 'Pelvis', NULL, NULL, '{1,2,3}'),
('96', 'Abdomen', 'BODYPART01', 'BODYPART11', '', 'Abdomen', NULL, NULL, '{1,2,3}'),
('97', 'Wrists', 'BODYPART22', 'BODYPART12', '', 'Muñecas', NULL, NULL, '{1,2,3}'),
('98', 'Legs', 'BODYPART01', 'BODYPART13', '', 'Piernas', NULL, NULL, '{1,2,3}'),
('99', 'Knee', 'BODYPART13', 'BODYPART14', '', 'Rodilla', NULL, NULL, '{1,2,3}'),
('100', 'Elbow', 'BODYPART22', 'BODYPART15', '', 'Codo', NULL, NULL, '{1,2,3}'),
('101', 'Lower Arm', 'BODYPART22', 'BODYPART16', '', 'Antebrazo', NULL, NULL, '{1,2,3}'),
('102', 'Upper Arm', 'BODYPART22', 'BODYPART17', '', 'Parte superior del brazo', NULL, NULL, '{1,2,3}'),
('103', 'Lower Leg', 'BODYPART13', 'BODYPART18', '', 'Pierna inferior', NULL, NULL, '{1,2,3}'),
('104', 'Upper Leg', 'BODYPART13', 'BODYPART19', '', 'Muslo', NULL, NULL, '{1,2,3}'),
('105', 'Upper Back', 'BODYPART01', 'BODYPART20', '', 'Superior de la espalda', NULL, NULL, '{1,2,3}'),
('106', 'Butt', 'BODYPART01', 'BODYPART21', '', 'Extremo', NULL, NULL, '{1,2,3}'),
('107', 'Arms', 'BODYPART01', 'BODYPART22', '', 'Brazos', NULL, NULL, '{1,2,3}'),
('108', 'Feet', 'BODYPART13', 'BODYPART23', '', 'Pies', NULL, NULL, '{1,2,3}'),
('109', 'Tongue', 'BODYPART06', 'BODYPART26', '', 'Lengua', NULL, NULL, '{1,2,3}'),
('110', 'Lips', 'BODYPART06', 'BODYPART27', '', 'Labios', NULL, NULL, '{1,2,3}'),
('111', 'Gums & Teeth', 'BODYPART06', 'BODYPART29', '', 'Gomas y dientes', NULL, NULL, '{1,2,3}'),
('112', 'Neck', 'BODYPART02', 'BODYPART31', '', 'Cuello', NULL, NULL, '{1,2,3}'),
('113', 'Roof Of Mouth', 'BODYPART06', 'BODYPART34', '', 'Techo de la boca', NULL, NULL, '{1,2,3}'),
('114', 'Back of Throat', 'BODYPART06', 'BODYPART35', '', 'Parte posterior de la garganta', NULL, NULL, '{1,2,3}'),
('115', 'Whole Body', '', 'PAIN_BODYPART01', 'BODYPART01', 'Todo el cuerpo', NULL, NULL, '{1,2,3}'),
('116', 'Head', 'PAIN_BODYPART01', 'PAIN_BODYPART02', 'BODYPART02', 'Cabeza', NULL, NULL, '{1,2,3}'),
('117', 'Nose', 'PAIN_BODYPART02', 'PAIN_BODYPART03', 'BODYPART03', 'Nariz', NULL, NULL, '{1,2,3}'),
('118', 'Throat', 'PAIN_BODYPART02', 'PAIN_BODYPART04', 'BODYPART04', 'Garganta', NULL, NULL, '{1,2,3}'),
('119', 'Chest', 'PAIN_BODYPART01', 'PAIN_BODYPART05', 'BODYPART05', 'Pecho', NULL, NULL, '{1,2,3}'),
('120', 'Mouth', 'PAIN_BODYPART02', 'PAIN_BODYPART06', 'BODYPART06', 'Boca', NULL, NULL, '{1,2,3}'),
('121', 'Right Eye', 'PAIN_BODYPART02', 'PAIN_BODYPART07', 'BODYPART07', 'Ojo derecho', NULL, NULL, '{1,2,3}'),
('122', 'Right Ear', 'PAIN_BODYPART02', 'PAIN_BODYPART08', 'BODYPART08', 'Oreja derecha', NULL, NULL, '{1,2,3}'),
('123', 'Forehead', 'PAIN_BODYPART02', 'PAIN_BODYPART09', 'BODYPART09', 'Frente', true, true, '{1,2,3}'),
('124', 'Pelvis', 'PAIN_BODYPART01', 'PAIN_BODYPART10', 'BODYPART10', 'Pelvis', NULL, NULL, '{1,2,3}'),
('125', 'Abdomen', 'PAIN_BODYPART01', 'PAIN_BODYPART11', 'BODYPART11', 'Abdomen', NULL, NULL, '{1,2,3}'),
('126', 'Right Wrist', 'PAIN_BODYPART22', 'PAIN_BODYPART12', 'BODYPART12', 'Muñeca derecha', NULL, NULL, '{1,2,3}'),
('127', 'Right Leg', 'PAIN_BODYPART01', 'PAIN_BODYPART13', 'BODYPART13', 'Pierna derecha', NULL, NULL, '{1,2,3}'),
('128', 'Right Knee', 'PAIN_BODYPART13', 'PAIN_BODYPART14', 'BODYPART14', 'Rodilla derecha', true, true, '{1,2,3}'),
('129', 'Right Elbow', 'PAIN_BODYPART22', 'PAIN_BODYPART15', 'BODYPART15', 'Codo derecho', true, true, '{1,2,3}'),
('130', 'Right Lower Arm', 'PAIN_BODYPART22', 'PAIN_BODYPART16', 'BODYPART16', 'Brazo inferior derecho', true, true, '{1,2,3}'),
('131', 'Right Upper Arm', 'PAIN_BODYPART22', 'PAIN_BODYPART17', 'BODYPART17', 'Brazo superior derecho', true, true, '{1,2,3}'),
('132', 'Right Lower Leg', 'PAIN_BODYPART13', 'PAIN_BODYPART18', 'BODYPART18', 'Pata inferior derecha', true, true, '{1,2,3}'),
('133', 'Right Upper Leg', 'PAIN_BODYPART13', 'PAIN_BODYPART19', 'BODYPART19', 'Pata superior derecha', true, true, '{1,2,3}'),
('134', 'Upper Back', 'PAIN_BODYPART01', 'PAIN_BODYPART20', 'BODYPART20', 'Superior de la espalda', NULL, NULL, '{1,2,3}'),
('135', 'Butt', 'PAIN_BODYPART01', 'PAIN_BODYPART21', 'BODYPART21', 'Extremo', NULL, NULL, '{1,2,3}'),
('136', 'Right Arm', 'PAIN_BODYPART01', 'PAIN_BODYPART22', 'BODYPART22', 'Brazo derecho', NULL, NULL, '{1,2,3}'),
('137', 'Right Ankle', 'PAIN_BODYPART13', 'PAIN_BODYPART23', 'BODYPART45', 'Tobillo derecho', true, true, '{1,2,3}'),
('138', 'Scalp', 'PAIN_BODYPART02', 'PAIN_BODYPART24', 'BODYPART57', 'Cuero cabelludo', true, true, '{1,2,3}'),
('139', 'Upper Left Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART59', 'BODYPART49', 'Abdomen superior izquierdo', true, true, '{1,2,3}'),
('140', 'Upper Center Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART60', 'BODYPART48', 'Abdomen central superior', true, true, '{1,2,3}'),
('141', 'Upper Right Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART61', 'BODYPART47', 'Abdomen superior derecho', true, true, '{1,2,3}'),
('142', 'Middle Left Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART62', 'BODYPART52', 'Abdomen medio izquierdo', true, true, '{1,2,3}'),
('143', 'Middle Center Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART63', 'BODYPART51', 'Centro Medio Abdomen', true, true, '{1,2,3}'),
('144', 'Middle Right Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART64', 'BODYPART50', 'Abdomen medio derecho', true, true, '{1,2,3}'),
('145', 'Lower Left Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART65', 'BODYPART55', 'Abdomen inferior izquierdo', true, true, '{1,2,3}'),
('146', 'Lower Center Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART66', 'BODYPART54', 'Abdomen central inferior', true, true, '{1,2,3}'),
('147', 'Lower Right Abdomen', 'PAIN_BODYPART11', 'PAIN_BODYPART67', 'BODYPART53', 'Abdomen inferior derecho', true, true, '{1,2,3}'),
('148', 'Upper Left Abdomen', 'SW_BODYPART11', 'SW_BODYPART59', 'BODYPART49', 'Abdomen superior izquierdo', true, true, '{1,2,3}'),
('149', 'Upper Center Abdomen', 'SW_BODYPART11', 'SW_BODYPART60', 'BODYPART48', 'Abdomen central superior', true, true, '{1,2,3}'),
('150', 'Upper Right Abdomen', 'SW_BODYPART11', 'SW_BODYPART61', 'BODYPART47', 'Abdomen superior derecho', true, true, '{1,2,3}'),
('151', 'Middle Left Abdomen', 'SW_BODYPART11', 'SW_BODYPART62', 'BODYPART52', 'Abdomen medio izquierdo', true, true, '{1,2,3}'),
('152', 'Middle Center Abdomen', 'SW_BODYPART11', 'SW_BODYPART63', 'BODYPART51', 'Centro Medio Abdomen', true, true, '{1,2,3}'),
('153', 'Middle Right Abdomen', 'SW_BODYPART11', 'SW_BODYPART64', 'BODYPART50', 'Abdomen medio derecho', true, true, '{1,2,3}'),
('154', 'Lower Left Abdomen', 'SW_BODYPART11', 'SW_BODYPART65', 'BODYPART55', 'Abdomen inferior izquierdo', true, true, '{1,2,3}'),
('155', 'Lower Center Abdomen', 'SW_BODYPART11', 'SW_BODYPART66', 'BODYPART54', 'Abdomen central inferior', true, true, '{1,2,3}'),
('156', 'Lower Right Abdomen', 'SW_BODYPART11', 'SW_BODYPART67', 'BODYPART53', 'Abdomen inferior derecho', true, true, '{1,2,3}'),
('157', 'Ankles', 'BODYPART13', 'BODYPART45', '', 'Tobillos', NULL, NULL, '{1,2,3}'),
('158', 'Toes', 'BODYPART13', 'BODYPART46', '', 'Dedos de los pies', NULL, NULL, '{1,2,3}'),
('159', 'Right Hand', 'PAIN_BODYPART22', 'PAIN_BODYPART72', 'BODYPART36', 'Mano derecha', NULL, NULL, '{1,2,3}'),
('160', 'Right Thumb', 'PAIN_BODYPART22', 'PAIN_BODYPART73', 'BODYPART37', 'Pulgar derecho', NULL, NULL, '{1,2,3}'),
('161', 'Right Fingers', 'PAIN_BODYPART22', 'PAIN_BODYPART74', 'BODYPART38', 'Dedos derechos', NULL, NULL, '{1,2,3}'),
('162', 'Left Hand', 'PAIN_BODYPART34', 'PAIN_BODYPART75', 'BODYPART36', 'Mano izquierda', NULL, NULL, '{1,2,3}'),
('163', 'Left Thumb', 'PAIN_BODYPART34', 'PAIN_BODYPART76', 'BODYPART37', 'Pulgar izquierdo', NULL, NULL, '{1,2,3}'),
('164', 'Left Fingers', 'PAIN_BODYPART34', 'PAIN_BODYPART77', 'BODYPART38', 'Dedos izquierdos', NULL, NULL, '{1,2,3}'),
('165', 'Right Hand', 'SW_BODYPART22', 'SW_BODYPART72', 'BODYPART36', 'Mano derecha', NULL, NULL, '{1,2,3}'),
('166', 'Right Thumb', 'SW_BODYPART22', 'SW_BODYPART73', 'BODYPART37', 'Pulgar derecho', NULL, NULL, '{1,2,3}'),
('167', 'Right Fingers', 'SW_BODYPART22', 'SW_BODYPART74', 'BODYPART38', 'Dedos derechos', NULL, NULL, '{1,2,3}'),
('168', 'Left Hand', 'SW_BODYPART34', 'SW_BODYPART75', 'BODYPART36', 'Mano izquierda', NULL, NULL, '{1,2,3}'),
('169', 'Left Thumb', 'SW_BODYPART34', 'SW_BODYPART76', 'BODYPART37', 'Pulgar izquierdo', NULL, NULL, '{1,2,3}'),
('170', 'Left Fingers', 'SW_BODYPART34', 'SW_BODYPART77', 'BODYPART38', 'Dedos izquierdos', NULL, NULL, '{1,2,3}'),
('171', 'Hands', 'BODYPART22', 'BODYPART36', '', 'Manos', NULL, NULL, '{1,2,3}'),
('172', 'Thumbs', 'BODYPART22', 'BODYPART37', '', 'Pulgares', NULL, NULL, '{1,2,3}'),
('173', 'Fingers', 'BODYPART22', 'BODYPART38', '', 'Dedos', NULL, NULL, '{1,2,3}'),
('174', 'Lower Back', 'BODYPART01', 'BODYPART41', '', 'Espalda baja', NULL, NULL, '{1,2,3}'),
('175', 'Lower Back', 'PAIN_BODYPART01', 'PAIN_BODYPART78', 'BODYPART41', 'Espalda baja', NULL, NULL, '{1,2,3}'),
('176', 'Lower Back', 'SW_BODYPART01', 'SW_BODYPART78', 'BODYPART41', 'Espalda baja', NULL, NULL, '{1,2,3}'),
('177', 'Armpits', 'BODYPART05', 'BODYPART42', '', 'Axilas', NULL, NULL, '{1,2,3}'),
('178', 'Nipples', 'BODYPART05', 'BODYPART43', '', 'Pezones', NULL, NULL, '{1,2,3}'),
('179', 'Breasts', 'BODYPART05', 'BODYPART44', '', 'Pechos', NULL, NULL, '{1,2,3}'),
('180', 'Right Armpit', 'PAIN_BODYPART05', 'PAIN_BODYPART79', 'BODYPART42', 'Axila derecha', NULL, NULL, '{1,2,3}'),
('181', 'Left Armpit', 'PAIN_BODYPART05', 'PAIN_BODYPART80', 'BODYPART42', 'Axila izquierda', NULL, NULL, '{1,2,3}'),
('182', 'Right Armpit', 'SW_BODYPART05', 'SW_BODYPART79', 'BODYPART42', 'Axila derecha', NULL, NULL, '{1,2,3}'),
('183', 'Left Armpit', 'SW_BODYPART05', 'SW_BODYPART80', 'BODYPART42', 'Axila izquierda', NULL, NULL, '{1,2,3}'),
('184', 'Right Foot', 'PAIN_BODYPART13', 'PAIN_BODYPART91', 'BODYPART23', 'Pie derecho', NULL, NULL, '{1,2,3}'),
('185', 'Right Toes', 'PAIN_BODYPART13', 'PAIN_BODYPART92', 'BODYPART46', 'Derechas', NULL, NULL, '{1,2,3}'),
('186', 'Left Foot', 'PAIN_BODYPART27', 'PAIN_BODYPART93', 'BODYPART23', 'Pie izquierdo', NULL, NULL, '{1,2,3}'),
('187', 'Left Toes', 'PAIN_BODYPART27', 'PAIN_BODYPART94', 'BODYPART46', 'Dedos del pie izquierdo', NULL, NULL, '{1,2,3}'),
('188', 'Right Foot', 'SW_BODYPART13', 'SW_BODYPART91', 'BODYPART23', 'Pie derecho', NULL, NULL, '{1,2,3}'),
('189', 'Right Toes', 'SW_BODYPART13', 'SW_BODYPART92', 'BODYPART46', 'Derechas', NULL, NULL, '{1,2,3}'),
('190', 'Left Foot', 'SW_BODYPART27', 'SW_BODYPART93', 'BODYPART23', 'Pie izquierdo', NULL, NULL, '{1,2,3}'),
('191', 'Left Toes', 'SW_BODYPART27', 'SW_BODYPART94', 'BODYPART46', 'Dedos del pie izquierdo', NULL, NULL, '{1,2,3}'),
('192', 'Upper Right Abdomen', 'BODYPART11', 'BODYPART47', '', 'Abdomen superior derecho', NULL, NULL, '{1,2,3}'),
('193', 'Upper Center Abdomen', 'BODYPART11', 'BODYPART48', '', 'Abdomen central superior', NULL, NULL, '{1,2,3}'),
('194', 'Upper Left Abdomen', 'BODYPART11', 'BODYPART49', '', 'Abdomen superior izquierdo', NULL, NULL, '{1,2,3}'),
('195', 'Middle Right Abdomen', 'BODYPART11', 'BODYPART50', '', 'Abdomen medio derecho', NULL, NULL, '{1,2,3}'),
('196', 'Middle Center Abdomen', 'BODYPART11', 'BODYPART51', '', 'Centro Medio Abdomen', NULL, NULL, '{1,2,3}'),
('197', 'Middle Left Abdomen', 'BODYPART11', 'BODYPART52', '', 'Abdomen medio izquierdo', NULL, NULL, '{1,2,3}'),
('198', 'Lower Right Abdomen', 'BODYPART11', 'BODYPART53', '', 'Abdomen inferior derecho', NULL, NULL, '{1,2,3}'),
('199', 'Lower Center Abdomen', 'BODYPART11', 'BODYPART54', '', 'Abdomen central inferior', NULL, NULL, '{1,2,3}'),
('200', 'Lower Left Abdomen', 'BODYPART11', 'BODYPART55', '', 'Abdomen inferior izquierdo', NULL, NULL, '{1,2,3}'),
('201', 'Back Head', 'BODYPART02', 'BODYPART56', '', 'Cabeza trasera', NULL, NULL, '{1,2,3}'),
('202', 'Scalp', 'BODYPART02', 'BODYPART57', '', 'Cuero cabelludo', NULL, NULL, '{1,2,3}'),
('203', 'Metabolic Panel', '', 'SYMPTCG16', '', 'Panel metabólico', NULL, NULL, '{1,2,3}'),
('204', 'Urinalysis', '', 'SYMPTCG17', '', 'Análisis de orina', NULL, NULL, '{1,2,3}'),
('205', 'Lipids', '', 'SYMPTCG18', '', 'Lípidos', NULL, NULL, '{1,2,3}'),
('206', 'CBC', '', 'SYMPTCG19', '', 'CBC', NULL, NULL, '{1,2,3}'),
('207', 'Other', '', 'SYMPTCG20', '', 'Otro', NULL, NULL, '{1,2,3}'),
('208', 'CSF', '', 'SYMPTCG21', '', 'CSF', NULL, NULL, '{1,2,3}'),
('209', 'Shoulders', 'BODYPART22', 'BODYPART58', '', 'Espalda', NULL, NULL, '{1,2,3}'),
('210', 'Fetal/Neonatal Observations', '', 'SYMPTCG22', '', 'Observaciones fetales', NULL, NULL, '{1,2,3}'),
('211', 'Imaging', '', 'SYMPTCG23', '', 'Imágenes', NULL, NULL, '{1,2,3}'),
('212', 'Right Shoulder', 'PAIN_BODYPART17', 'PAIN_BODYPART95', 'BODYPART58', '', NULL, NULL, '{1,2,3}'),
('213', 'Left Shoulder', 'PAIN_BODYPART31', 'PAIN_BODYPART96', 'BODYPART58', '', NULL, NULL, '{1,2,3}'),
('214', 'Right Hip', 'PAIN_BODYPART13', 'PAIN_BODYPART97', 'BODYPART59', '', NULL, NULL, '{1,2,3}'),
('215', 'Left Hip', 'PAIN_BODYPART27', 'PAIN_BODYPART98', 'BODYPART59', '', NULL, NULL, '{1,2,3}'),
('216', 'Right Shoulder', 'SW_BODYPART17', 'SW_BODYPART95', 'BODYPART58', 'Hombro derecho', NULL, NULL, '{1,2,3}'),
('217', 'Left Shoulder', 'SW_BODYPART31', 'SW_BODYPART96', 'BODYPART58', 'Hombro izquierdo', NULL, NULL, '{1,2,3}'),
('218', 'Right Hip', 'SW_BODYPART13', 'SW_BODYPART97', 'BODYPART59', 'Cadera derecha', NULL, NULL, '{1,2,3}'),
('219', 'Left Hip', 'SW_BODYPART27', 'SW_BODYPART98', 'BODYPART59', 'Cadera izquierda', NULL, NULL, '{1,2,3}'),
('220', 'Hip', 'BODYPART13', 'BODYPART59', '', 'Caderas', NULL, NULL, '{1,2,3}'),
('221', 'Physical Exam', '', 'SYMPTCG24', '', 'Examen físico', NULL, NULL, '{1,2,3}'),
('222', 'Stool', '', 'SYMPTCG25', '', 'Taburete', NULL, NULL, '{1,2,3}'),
('223', 'Screenings', '', 'SYMPTCG26', '', 'Psicológico', NULL, NULL, '{1,2,3}'),
('224', 'PTSD', '', 'SYMPTCG27', '', 'PTSD', NULL, NULL, '{1,2,3}'),
('225', 'Core Symptoms', '', 'SYMPTCG28', '', 'Síntomas principales', NULL, NULL, '{1,2,3}'),
('226', 'Pathology', '', 'SYMPTCG29', '', 'Patología', NULL, NULL, '{1,2,3}'),
('227', 'Temporals', 'BODYPART02', 'BODYPART60', '', 'Temporals', NULL, NULL, '{1,2,3}'),
('228', 'Microbiology', '', 'SYMPTCG30', '', 'Microbiología', NULL, NULL, '{1,2,3}'),
('229', 'Tumor Markers', '', 'SYMPTCG31', '', 'Marcadores tumorales', NULL, NULL, '{1,2,3}'),
('230', 'Arterial Blood Gas', '', 'SYMPTCG32', '', 'Gasometría Arterial', NULL, NULL, '{1,2,3}'),
('231', 'Core Symptoms', '', 'SYMPTCG33', '', 'Síntomas principales', NULL, NULL, '{1,2,3}'),
('232', 'Eyelids', 'SW_BODYPART07', 'SW_BODYPART101', 'BODYPART61', '', NULL, NULL, '{1,2,3}'),
('233', 'Chest', 'BODYPART01', 'BODYPART05', '', 'Cofre', NULL, NULL, '{1,2,3}'),
('234', 'Eyelids', 'BODYPART07', 'BODYPART61', '', '', NULL, NULL, '{1,2,3}'),
('235', 'Breasts', 'PAIN_BODYPART05', 'PAIN_BODYPART99', 'BODYPART44', '', NULL, true, '{1,2,3}'),
('236', 'Nipples', 'PAIN_BODYPART05', 'PAIN_BODYPART100', 'BODYPART43', '', NULL, true, '{1,2,3}'),
('237', 'Eyelids', 'PAIN_BODYPART07', 'PAIN_BODYPART101', 'BODYPART61', '', NULL, NULL, '{1,2,3}'),
('238', 'Breasts', 'SW_BODYPART05', 'SW_BODYPART99', 'BODYPART44', '', NULL, true, '{1,2,3}'),
('239', 'Nipples', 'SW_BODYPART05', 'SW_BODYPART100', 'BODYPART43', '', NULL, true, '{1,2,3}'),
('240', 'Assessment/Evaluation', '', 'SYMPTCG34', '', 'Valoración / Evaluación', NULL, NULL, '{1,2,3}'),
('241', 'Core Symptoms', '', 'SYMPTCG35', '', 'Síntomas principales', NULL, NULL, '{1,2,3}')"""
    cursor = connection.cursor()
    cursor.execute(postgreSql_insert_query)
    connection.commit()
    print(cursor.rowcount, "Record inserted successfully into SymptomCategory table")
    cursor.close()
except psycopg2.OperationalError as error:
    print("Failed to insert record into SnomedCode table {}".format(error))