export const SGDKArr = [
[ 1, ["BleedingDisorder","CHC","SkinDisorders","RecentMedialCare","Medications","GynaecologyHistory","Ethnicity","TimeUnit","RHTI","Slope","RheumatoidDisease","PregnancyIssues","MedicalCare","CancerTreatment","Treatment","ConcurrentIllness","HeartDisease","AdverseReaction","CDefect","STD","PreviousIllness","Season","FirstDrink","Recurs","DrinksPerDay","BloodClots","RecurrentInfections","Gender","BloodDisease","RenalDisease","Importance","Drug","OralDisease","EyeIssue","Orientation","Ldiseases","EndocrineDisease","BoneIssues","Cancer","PMentalDisorders","RespiratoryDisease","ToeNailInfection","Timebucket","VascularDisease","AlcoholConsumption","Diabetes","RBacteria","Likelihood","NeurologicalDisease","AllergyMedication","Allergy","LiverDisease","ArteryDiseases","MedicalImplant","IntakeMethod","Age","SkinConditions","Immunization","IllnessExtenalService","SpinalIssues","Children","GeneticDisorder","OrganTransplanted","FMentalDisorders","GastrointestinalIssues","Alcohol","HTrauma"], ],
[ 2, ["ObFeelings","CLLQ","Ethnicity","TimeUnit","Slope","FoodSubstance","Temperature","JobExposures","ChangeInLibido","Animals","PoorSleepReasons","Jobs","Recurs","LastDiet","SubstanceExposure","PhysicallyActive","Importance","ExposureLevel","SociallyOutgoing","BabyDiet","Change","EnergyLevel","JobBehavior","IVAccess","Timebucket","DietaryHabits","TropicalClimate","FamilyStructure","ImportanceWeight","Country","Likelihood","travel","Infections","DietContent","HallucinationSleep","Cravings","JobStress","DK590","Addiction","SleepingPatterns","WaterAreas"], ],
[ 3, ["Recurs","Feeling","WorseBy","CannotRecognize","ThoughtProcess","AbnormalSpeech","Hallucinations","Abuse","Ethnicity","MemoryIssues","NegativeBody","DifficultyMovements","FearOf","EmotionalControl","Behavior","Delusions","Likelihood","TimeUnit","MotorDevelopment","AuditoryHallucinations","Slope","CauseForInability","Timebucket","SuicidalBehavior","CompulsiveBehaviour","ArousalBy","Importance"], ],
[ 4, ["PupilSizeChange","RPS","Nystagmus","BruiseDescription","TesticlesSide","BloodyStoolDescriptor","WeightChange","TasteAssociation","CoughAssociation","CoughFluids","DK589","TouchSensitivity","Likelihood","PregnancyLength","DK587","TwitchingMuscle","DK585","DK584","Ethnicity","BreathingProblems","DK582","DK581","DK580","TasteAggravated","HeadTrauma","Paralysis","TurnedDirection","ColdTime","BicepMovement","FaceNumbness","HipMovement","TasteChange","EEI","Discoloration","PeriodsAge","DK579","ExfoliationPercentage","ElbowMovement","BreastTexture","FlankPain","VoiceDescription","Abnormality","MoleDiameter","ScalpRash","PeriodsFrequency","Onset","RashTextureDescription","BurnPercentage","HPD","NailAbnormalities","FaceColor","TeethDamage","MoleBorder","PWSUH","SkinTexture","Menstruating","InsectBite","VaginalLesion","Menopause","Intoxicated","TeethDeposit","PuncturedBy","BlisterDescription","CoughTime","NailDiscoloration","HairLoss","HemiparesisSide","DifficultySwallow","TimeUnit","NailBedDiscoloration","AnalDischarge","EyelidLoc","NoseDischarge","Recurs","UrineDescription","RashColorDescription","RashShapeDescription","DischargeDescription","NTC","NTB","RashTrigger","SkinDiscoloration","VisionProblems","RTMP","LBPA","RashChange","EyeDischarge","Importance","MoleColor","Pigmentation","PainStartedSomewhereElse","WristMovement","EyeDiscoloration","VD","VC","NasalCongestion","NeckMovement","Posture","MenstruationFlow","TasteStops","StoolConsistency","HearingLoss","EyelidInfla","Taste","ForearmMovement","CoughDescription","UrineColor","KneeMovement","RashSize","MuscleInjury","VaginalDischargeDescription","RectalBleeding","ShortnessOfBreath","MoleChange","Hearing","UterusDischarge","DiscolorationReason","NRB","NT","BodySide","BirthControl","ShoulderMovement","Timebucket","EarColor","RDP","Slope","EarDischarge","BMS"], ],
[ 5, ["Recurs","PainDescription","EarSwellingLocation","SwellingDescription","LocationOfPain","RChestPain","Ethnicity","PainTime","JawPain","HeadacheDescription","NewLocationOfPain","PainReliefFrom","Likelihood","TimeUnit","Onset","Slope","SinusTenderness","PainStance","PainTiming","Timebucket","APA","PainScale","SwellingLocation","ChestArea","PainStartedSomewhereElse","EarPainLocation","PainWorsenBy","Importance"], ],
[ 6, ["PhysicalAppearance","RespiratorySounds","PenisExamDescription","Anxiety","UpperExtremityStrengthDescription","EyeLidExam","NVIIIDescription","CognitionDescription","PostureDescription","Ophtalmoscopic","RightExternalEarDescription","Likelihood","LowerExtremityStrenghtDescription","DK586","SuicideResults","BruisingExamDescription","DK583","Ethnicity","RashSpecificCharacteristicsDescription","Gait","NIDescription","GeneralPsyciatricObservationsDescription","NIIDescription","InjuryDescription","Cornea","NIII/IV/VIDescription","CervicalSpineExamDescription","NVDescription","CordParalysis","OtoscopeSkin","ProstateExam","NXIIDescription","RashDistributionDescription","OtoscopeMouth","Lens","Afrequency","WoundDescription","RashTextureDescription","BartholinGland","Depression","Pulse","TemperatureandTextureDescription","ExtremitiesDescription","CardiacSounds","DHManeuvar","EyeMovements","EKGResults","AbdominalExam","WoundHealing","OtoscopeNose","IrisSpot","Conjuctiva","TimeUnit","SensoryExamDescription","ThoughtsDescription","EyeExamsDescription","Recurs","NXIDescription","RashColorDescription","RashShapeDescription","ThyroidPalpation","EmotionsDescription","LegTest","BreastPalpationDescription","RespiratoryRate","Importance","RespiratoryEffortDescription","FemaleExternalGenitaliaDescription","EyeAcuity","NormalActivity","Pulmonary","BabinskiDescription","AcidBase","HepatoJugularRefluxDescription","LymphaticExamDescription","BenignSkinLesionDescription","RectalExam","Dyspnea","JugularVenousDistentionDescription","WeakPulse","GeneralAppearance","SkinLesionsDescription","Bipolar","HairDescription","LowerExtremityExamDescription","Endoscopy","AsthmaScreen","SmartBodyIndex","TestResult","ParotidExamDescription","DTRDescription","PeriorbitalEdemaDescription","NVIIDescription","Fever","RashArrangementDescription","NXDescription","ScrotalExamDescription","BreastInspectionDescription","RashTypeDescription","ETM","AbdominalInspectionDescription","BreathingPatterns","LeftExternalEarDescription","UrethralExamDescription","EarCanal","BimanualExamDescription","LevelofconsciousnessDescription","KneeExam","SaturationLevel","SuicideDescription","AbdomenSounds","ChestPercussionDescription","UpperExtermityExamDescription","RashMorphologyDescription","ThoracicSpine/RibsExamDescription","ChestPalpationDescription","NIXDescription","OtoscopeEar","ExternalNoseDescription","BloodPressure","BipolarProblem","Vaginal/CervixExamDescription","EyePressure","ColonoscopyResults","AbdominalPalpationDescription","HearingExamDescription","Slope","RashColorIntensityDescription"], ],
[ 7, ["Viscosity","Cholsterol","BLU","TSaturation","CTEar","Mif","BloodSmear","Coagulation","CRP","MRIBrain","ImmatureGrans","Elocation","RapidStrep","S-?HCG","UricAcid","VitaminB12","CTScan","Potassium","SPF","PVU","ImmatureGranulocytes","Rheumatological","MPV","SCT","Platelets","HBSA","Cfixation","UrineWBC","BUNRatio","Basophils","TUS","Bultrasound","Treponemal","MCV","RUS","KidneyBiopsy","UBT","Lymphocytes","SWBC","LDLHDLRatio","MCH","WBC","Ketones","CervicalXRay","HemoglobinA1C","Sbacteria","TestResult","EPF","ExcretionSodium","NeutrophilsAbsolute","KOH","Calcium","CSFColor","Culture","UrineUrobilinogen","Chloride","EOS","FerritinSerum","UrineLeukocyteEsterase","PTH","BASO","Mbiopsy","IgM","IgG","AbdominalCTContrast","Radiography","TSH","LymphocytesAbsolute","NAAT","SMC","Monocytes","Monospot","LaticAcid","Cpeptide","CO2","AlkalinePhosphate","Ghormone","VSSense","CK","AbdominalLocation","Importance","FOBT","PapSmear","AnionGap","Phosphate","ViralLoad","TestosteroneFree","Ctiers","RandomGlucose","EAG","RDWSD","TotalBilirubin","StomachpH","UrineSodium","AntiHEV","TestosteroneTotal","Tomography","ArterialpO2","Clarity","Creatinine","CreatinineUr24hr","ArterialpCo2","TIBC","RDU","Sodium","AntiHDV","ALT","ArterialHco3","Slocation","BariumSwallowResults","Magnesium","VCT","MCHC","Neutrophils","TPA","UrineColor","UrineBacteria","LeftVentricle","Dimer","LDH","PPD","Nontreponemal","Pericardiam","PCR","Glucose","NRBC","Osmolarity","Bun","BloodInUrine","T4Free","HDLCholestrol","Bdirect","AbdominalCT","UrineRBC","UrineBilirubin","MRIKnee","GlucoseOGTT","CWC","RDWCV","ArteriesStenosis","Likelihood","CTHead","TotalProtein","AgglutininTiter","Arthroconidium","EjectionFraction","RBC","UrineSpecficGravity","Mammogram","PelvicUltrasound","CTSinus","Triglycerides","ArterialpH","SquamousEpthelialUrine","Hemoglobin","EUS","Mumps","UrineGlucose","CUS","Albumin","IGGRT","GlucoseFasting","PHUrine","TotalGlobulin","IronLevel","ProteinUrine","Hematocrit","eGFR","MRIOrbit","MonocytesAbsolute","SeptalDefect","NitriteUrine","AlbuminUrine","VLDLCholesterol","BNP","GramStain","Ultrasound","FolateSerum","HILocation","Color","CTOrbit","ChestXrayResult","CTE","LDLCholesterol","Canalysis","UrineSediment","EMRI","AGRatio","T3Free","HepD","ESR","GastrinLevels","CreatinineAlbumin","HepC","TBiopsy","HepB","HepA","CultureLocation","SMRI","ELISA","AST","TestosteroneSerum","pKINR","Eosinophils","Recurs","VitaminD25Hydroxy","CTABrain"], ],
[ 8, ["Likelihood","PhysicalActivity","Slope","Recurs","Fell","SpecificSport","Overdose","Importance","Bite","Accident"], ],
[ 9, ["Likelihood","Importance"], ],
[ 10, ["IT","Recurs","FMNE","FMCO","FMR","FMGU","FMMU","FMCA","VT","FMPS","IOS","FMAL","OWT","Likelihood","FMENT","TimeUnit","FMEY","FMGI","JI","FMSK","Slope","SI","FMEN","SIT","FMLY","Importance"], ],
]
export const DKSArr = [
[ 1, 'EarDischarge', 'Ear Discharge', 'Secreción del oído', 'DK071' ],
[ 2, 'SubstanceExposure', 'Substance Exposure', 'Exposición a sustancias', 'DK072' ],
[ 3, 'UrineDescription', 'Urine Description', 'Descripción de la orina', 'DK073' ],
[ 4, 'BlisterDescription', 'Blister Description', 'Descripción de la ampolla', 'DK074' ],
[ 5, 'BruiseDescription', 'Bruise Description', 'Descripción de la contusión', 'DK075' ],
[ 6, 'HemiparesisSide', 'Hemiparesis Side', 'Hemiparesia Lateral', 'DK077' ],
[ 7, 'Hearing', 'Hearing', 'Audición', 'DK078' ],
[ 8, 'Children', 'Children', 'Niños', 'DK079' ],
[ 9, 'GastrointestinalIssues', 'Gastrointestinal Issue', 'Problema gastrointestinal', 'DK080' ],
[ 10, 'RenalDisease', 'Renal Disease', 'Enfermedad renal', 'DK081' ],
[ 11, 'LiverDisease', 'Liver Disease', 'Enfermedad del higado', 'DK082' ],
[ 12, 'Pigmentation', 'Pigmentation Condition', 'Condición de la pigmentación', 'DK083' ],
[ 13, 'BloodyStoolDescriptor', 'Description', 'Descripción', 'DK085' ],
[ 14, 'StoolConsistency', 'Stool Consistency', 'Consistencia del taburete', 'DK086' ],
[ 15, 'MoleDiameter', 'Mole Diameter', 'Diámetro del topo', 'DK088' ],
[ 16, 'RashSize', 'Change in Rash Size', 'Cambio en el tamaño de la erupción', 'DK089' ],
[ 17, 'MoleChange', 'Change in Mole', 'Cambio en Mole', 'DK090' ],
[ 18, 'RashChange', 'Type of Rash Change', 'Tipo de cambio de erupción', 'DK091' ],
[ 19, 'CarotidsNormal', 'Carotids Normal', '', 'DK722' ],
[ 20, 'UterusDischarge', 'Uterus Discharge', 'Descarga de útero', 'DK093' ],
[ 21, 'IntakeMethod', 'Intake Method', 'Método de ingesta', 'DK094' ],
[ 22, 'TwitchingMuscle', 'Twitching Muscle', 'Músculo de contracción', 'DK095' ],
[ 23, 'SkinDiscoloration', 'Skin Discoloration', 'Decoloración de la piel', 'DK097' ],
[ 24, 'WeightChange', 'Weight Change', 'Cambio de peso', 'DK098' ],
[ 25, 'ScalpRash', 'Scalp Rash', 'Erupción del cuero cabelludo', 'DK100' ],
[ 26, 'TropicalClimate', 'Tropical Climate', 'Clima tropical', 'DK101' ],
[ 27, 'BreastTexture', 'Breast Texture', 'Textura de los senos', 'DK102' ],
[ 28, 'VaginaPain', 'Vagina Pain', 'Dolor de la vagina', 'DK103' ],
[ 29, 'Medications', 'Medication', 'Medicación', 'DK104' ],
[ 30, 'ColdTime', 'Time', 'Hora', 'DK105' ],
[ 31, 'AlcoholConsumption', 'Alcohol Consumption', 'Consumo de alcohol', 'DK107' ],
[ 32, 'GeneticDisorder', 'Genetic Disorder', 'Trastorno genético', 'DK108' ],
[ 33, 'AllergyMedication', 'Medication', 'Medicación', 'DK109' ],
[ 34, 'BloodClots', 'Blood Clot', 'Coágulo de sangre', 'DK110' ],
[ 35, 'BloodDisease', 'Blood Disease', 'Enfermedad de la sangre', 'DK111' ],
[ 36, 'BoneIssues', 'Bone Issues', 'Problemas óseos', 'DK112' ],
[ 37, 'DrinksPerDay', 'Drinks per Day', 'Bebidas por dia', 'DK113' ],
[ 38, 'FirstDrink', 'First Drink', 'Primera bebida', 'DK114' ],
[ 39, 'HeartDisease', 'Heart Disease', 'Enfermedad del corazón', 'DK115' ],
[ 40, 'RespiratoryDisease', 'Respiratory Disease', 'Enfermedad respiratoria', 'DK116' ],
[ 41, 'PregnancyIssues', 'Pregnancy Issue', 'Problema de embarazo', 'DK117' ],
[ 42, 'STD', 'STD', 'STD', 'DK118' ],
[ 43, 'SkinDisorders', 'Skin Disorder', 'Trastorno de la piel', 'DK119' ],
[ 44, 'SpinalIssues', 'Spinal Issue', 'Problema de la columna vertebral', 'DK120' ],
[ 45, 'NeurologicalDisease', 'Neurological Disease', 'Enfermedad neurológica', 'DK121' ],
[ 46, 'EndocrineDisease', 'Endocrine Disease', 'Enfermedad endocrina', 'DK122' ],
[ 47, 'OralDisease', 'Oral Disease', 'Enfermedad oral', 'DK123' ],
[ 48, 'GynaecologyHistory', 'Gynecological History', 'Historia ginecologica', 'DK124' ],
[ 49, 'OtoscopeEar', 'Otoscope, Ear', 'Otoscopio, Oreja', 'DK125' ],
[ 50, 'NasalCongestion', 'Nasal Congestion', 'Congestión nasal', 'DK126' ],
[ 51, 'RespiratorySounds', 'Respiratory Sound', 'Sonido respiratorio', 'DK127' ],
[ 52, 'ChangeInLibido', 'Change in Libido', 'Cambio en la libido', 'DK128' ],
[ 53, 'Cravings', 'Craving', 'Ansia', 'DK129' ],
[ 54, 'DietaryHabits', 'Dietary Habit', 'Hábito dietético', 'DK130' ],
[ 55, 'ExposureLevel', 'Exposure Level', 'Nivel de exposición', 'DK131' ],
[ 56, 'Infections', 'Infections', 'Infecciones', 'DK132' ],
[ 57, 'BleedingDisorder', 'Bleeding Disorder', 'Desorden sangrante', 'DK133' ],
[ 58, 'CardiacSounds', 'Cardiac Sound', 'Sonido cardiaco', 'DK134' ],
[ 59, 'Hyperactive', 'Hyperactive', '', 'DK135' ],
[ 60, 'SaturationLevel', 'Saturation Level', 'Nivel de saturacion', 'DK136' ],
[ 61, 'PupilSizeChange', 'Change in Pupil Size', 'Cambio en el tamaño de la pupila', 'DK137' ],
[ 62, 'HearingLoss', 'Hearing Loss', 'Pérdida de la audición', 'DK139' ],
[ 63, 'MedicalImplant', 'Medical Implant', 'Implante medico', 'DK140' ],
[ 64, 'PuncturedBy', 'Punctured By', 'Perforado por', 'DK141' ],
[ 65, 'Posture', 'Posture', 'Postura', 'DK142' ],
[ 66, 'MoleColor', 'Mole Color', 'Mole Color', 'DK143' ],
[ 67, 'MoleBorder', 'Mole Border', 'Mole Border', 'DK144' ],
[ 68, 'TasteChange', 'Change in Taste', 'Cambio en el gusto', 'DK145' ],
[ 69, 'EyeIssue', 'Eye Issue', 'Problema de los ojos', 'DK146' ],
[ 70, 'OtoscopeNose', 'Scope Exam, Nose', 'Examen de alcance, la nariz', 'DK147' ],
[ 71, 'OtoscopeMouth', 'Scope Exam, Mouth', 'Examen de alcance, la boca', 'DK149' ],
[ 72, 'OtoscopeSkin', 'Scope Exam, Skin', 'Examen de alcance, piel', 'DK150' ],
[ 73, 'AuditoryHallucinations', 'Auditory Hallucinations', 'Alucinaciones auditivas', 'DK151' ],
[ 74, 'ShoulderMovement', 'Shoulder Movement', 'Movimiento del hombro', 'DK152' ],
[ 75, 'BicepMovement', 'Bicep Movement', 'Movimiento de bíceps', 'DK153' ],
[ 76, 'ElbowMovement', 'Elbow Movement', 'Movimiento del codo', 'DK154' ],
[ 77, 'ForearmMovement', 'Forearm Movement', 'Movimiento de antebrazo', 'DK155' ],
[ 78, 'NailAbnormalities', 'Nail Abnormalities', 'Anomalías en las uñas', 'DK156' ],
[ 79, 'WristMovement', 'Wrist Movement', 'Movimiento de la muñeca', 'DK157' ],
[ 80, 'HipMovement', 'Hip Movement', 'Movimiento de cadera', 'DK158' ],
[ 81, 'KneeMovement', 'Knee Movement', 'Movimiento de la rodilla', 'DK159' ],
[ 82, 'Menopause', 'Menopause', 'Menopausia', 'DK160' ],
[ 83, 'MenstruationFlow', 'Menstruation Flow', 'Flujo de la menstruación', 'DK161' ],
[ 84, 'Abnormality', 'Abnormality', 'Anormalidad', 'DK162' ],
[ 85, 'BirthControl', 'Birth Control', 'Control de la natalidad', 'DK163' ],
[ 86, 'MuscleInjury', 'Muscle Injury', 'Lesión muscular', 'DK164' ],
[ 87, 'InsectBite', 'Insect Bite', 'Picadura de insecto', 'DK166' ],
[ 88, 'SinusTenderness', 'Sinus Tenderness', 'Sinus ternura', 'DK170' ],
[ 89, 'TouchSensitivity', 'Touch Sensitivity', 'Sensibilidad táctil', 'DK172' ],
[ 90, 'CannotRecognize', 'Cannot Recognize', 'No se puede reconocer', 'DK173' ],
[ 91, 'NeckMovement', 'Neck Movement', 'Movimiento del cuello', 'DK175' ],
[ 92, 'ThoughtProcess', 'Thought Process', 'Proceso de pensamiento', 'DK176' ],
[ 93, 'ExfoliationPercentage', 'Exfoliation Percentage', 'Porcentaje de exfoliación', 'DK178' ],
[ 94, 'PainScale', 'Pain Scale', 'Escala del dolor', 'DK179' ],
[ 95, 'SwellingDescription', 'Swelling Description', 'Descripción de la hinchazón', 'DK180' ],
[ 96, 'PreviousIllness', 'Previous Illness', 'Enfermedad anterior', 'DK181' ],
[ 97, 'TeethDeposit', 'Teeth Deposit', 'Depósito de dientes', 'DK182' ],
[ 98, 'DiscolorationReason', 'Reason for Discoloration', 'Razón de la decoloración', 'DK183' ],
[ 99, 'RheumatoidDisease', 'Rheumatoid Disease', 'Enfermedad reumatoide', 'DK184' ],
[ 100, 'RightCarotidBruit', 'Right Carotid Bruit', '', 'DK723' ],
[ 101, 'LeftCarotidBruit', 'Left Carotid Bruit', '', 'DK724' ],
[ 102, 'Normal', 'Normal', '', 'DK725' ],
[ 103, 'NoabdomenBruit', 'No abdomen Bruit', '', 'DK726' ],
[ 104, 'Discharge', 'Discharge', '', 'DK727' ],
[ 105, 'Blood', 'Blood', '', 'DK728' ],
[ 106, 'Normal', 'Normal', '', 'DK729' ],
[ 107, 'Normal', 'Normal', '', 'DK730' ],
[ 108, 'PharyngealExudate', 'Pharyngeal Exudate', '', 'DK731' ],
[ 109, 'RightTonsilExudate', 'Right Tonsil Exudate', '', 'DK732' ],
[ 110, 'EKGResults', 'EKG Results', 'Resultados de EKG', 'DK187' ],
[ 111, 'RespiratoryRate', 'Respiratory Rate', 'La frecuencia respiratoria', 'DK201' ],
[ 112, 'Importance', 'Importance', 'Importancia', 'DK001' ],
[ 113, 'TimeUnit', 'Time Unit', 'Unidad de tiempo', 'DK002' ],
[ 114, 'Gender', 'Gender', 'Género', 'DK003' ],
[ 115, 'Slope', 'Slope', 'Cuesta abajo', 'DK004' ],
[ 116, 'Orientation', 'Orientation', 'Orientación', 'DK005' ],
[ 117, 'Season', 'Season', 'Temporada', 'DK006' ],
[ 118, 'Ethnicity', 'Ethnicity', 'Etnicidad', 'DK007' ],
[ 119, 'Drug', 'Drug', 'Fármaco', 'DK008' ],
[ 120, 'Allergy', 'Allergy', 'Alergia', 'DK009' ],
[ 121, 'Cancer', 'Cancer', 'Cáncer', 'DK010' ],
[ 122, 'Diabetes', 'Type', 'Tipo', 'DK011' ],
[ 123, 'Country', 'Geography', 'Geografía', 'DK013' ],
[ 124, 'Animals', 'Animals', 'Los animales', 'DK014' ],
[ 125, 'Temperature', 'Temperature', 'Temperatura', 'DK015' ],
[ 126, 'EmotionalControl', 'Behavior', 'Comportamiento', 'DK017' ],
[ 127, 'PoorSleepReasons', 'Reason', 'Razón', 'DK019' ],
[ 128, 'Addiction', 'Addiction', 'Adiccion', 'DK020' ],
[ 129, 'JobBehavior', 'Behavior', 'Comportamiento', 'DK021' ],
[ 130, 'EyeDiscoloration', 'Color', 'Color', 'DK026' ],
[ 131, 'VisionProblems', 'Problem', 'Problema', 'DK027' ],
[ 132, 'Taste', 'Taste', 'Gusto', 'DK028' ],
[ 133, 'TasteAssociation', 'Associated With', 'Asociado con', 'DK029' ],
[ 134, 'TasteAggravated', 'Aggravated By', 'Agravado por', 'DK030' ],
[ 135, 'TasteStops', 'Bad Taste Stops', 'Se detiene el mal gusto', 'DK031' ],
[ 136, 'Likelihood', 'Likelihood', 'Probabilidad', 'DK032' ],
[ 137, 'JobStress', 'Reason', 'Razón', 'DK033' ],
[ 138, 'Treatment', 'Treatment', 'Tratamiento', 'DK034' ],
[ 139, 'HeadTrauma', 'Trauma', 'Trauma', 'DK037' ],
[ 140, 'DischargeDescription', 'Discharge Description', 'Descripción de la descarga', 'DK040' ],
[ 141, 'CoughDescription', 'Cough Description', 'Tos descripción', 'DK041' ],
[ 142, 'CoughTime', 'Time of Cough', 'Tiempo de tos', 'DK043' ],
[ 143, 'CoughAssociation', 'Activity', 'Actividad', 'DK044' ],
[ 144, 'VaginalDischargeDescription', 'Vaginal Discharge Description', 'Descripción de la descarga vaginal', 'DK045' ],
[ 145, 'HairLoss', 'Area', 'Zona', 'DK047' ],
[ 146, 'NoseDischarge', 'Description', 'Descripción', 'DK048' ],
[ 147, 'HeadacheDescription', 'Description', 'Descripción', 'DK049' ],
[ 148, 'BloodPressure', 'Blood Pressure Level', 'Nivel de presion sanguinea', 'DK051' ],
[ 149, 'Pulse', 'Pulse Level', 'Nivel de pulso', 'DK052' ],
[ 150, 'SmartBodyIndex', 'Smart Body Index', 'Índice de cuerpo inteligente', 'DK053' ],
[ 151, 'WaterAreas', 'Water Area', 'Area de agua', 'DK054' ],
[ 152, 'Change', 'Change in Appetite', 'Cambio en el apetito', 'DK055' ],
[ 153, 'FoodSubstance', 'Food Substance', 'Sustancia alimenticia', 'DK056' ],
[ 154, 'Feeling', 'Feeling', 'Sensación', 'DK057' ],
[ 155, 'FearOf', 'Fear Of', 'Miedo de', 'DK058' ],
[ 156, 'PainDescription', 'Pain Description', 'Descripción del dolor', 'DK059' ],
[ 157, 'PainTime', 'Time of Day', 'Hora del dia', 'DK060' ],
[ 158, 'PainStance', 'Stance', 'Postura', 'DK061' ],
[ 159, 'PainWorsenBy', 'Made Worse By', 'Hecho peor por', 'DK062' ],
[ 160, 'PainStartedSomewhereElse', 'Body Parts', 'Partes del cuerpo', 'DK063' ],
[ 161, 'PainReliefFrom', 'Relief From', 'Alivio de', 'DK064' ],
[ 162, 'AdverseReaction', 'Adverse Drug Reaction', 'Reacción adversa al medicamento', 'DK065' ],
[ 163, 'FaceColor', 'Facial Discoloration', 'Decoloracion facial', 'DK066' ],
[ 164, 'DietContent', 'Diet Content', 'Contenido de la dieta', 'DK067' ],
[ 165, 'EarColor', 'Ear Color', 'Color de oreja', 'DK069' ],
[ 166, 'BloodAccumulation', 'Blood Accumulation', 'Acumulación de sangre', 'DK209' ],
[ 167, 'PregnancyLength', 'Pregnancy Length', 'Longitud del embarazo', 'DK203' ],
[ 168, 'AcidBase', 'Acid Base', 'Base ácida', 'DK202' ],
[ 169, 'ColonoscopyResults', 'Colonoscopy Result', 'Resultado de la colonoscopia', 'DK188' ],
[ 170, 'BariumSwallowResults', 'Barium Swallow Result', 'Resultado de la golondrina de bario', 'DK189' ],
[ 171, 'WorseBy', 'Worse By', 'Peor por', 'DK190' ],
[ 172, 'VascularDisease', 'Vascular Disease', 'Enfermedad vascular', 'DK191' ],
[ 173, 'DK591', 'Immunizations', 'undefined', 'DK591' ],
[ 174, 'OrganTransplanted', 'Organ Transplanted', 'Trasplante de órganos', 'DK185' ],
[ 175, 'BodySide', 'Body Side', 'Lado del cuerpo', 'DK186' ],
[ 176, 'ArteryDiseases', 'Artery Diseases', 'Enfermedades Arteriales', 'DK198' ],
[ 177, 'TesticlesSide', 'Testicle Side', 'Lado del testículo', 'DK207' ],
[ 178, 'MemoryIssues', 'Memory Issues', 'Problemas de memoria', 'DK193' ],
[ 179, 'EyeDischarge', 'Eye Discharge', 'Descarga ocular', 'DK194' ],
[ 180, 'TurnedDirection', 'Turned Direction', 'Direccion girada', 'DK195' ],
[ 181, 'CauseForInability', 'Cause for Inability', 'Causa de incapacidad', 'DK196' ],
[ 182, 'EarPainLocation', 'Ear Pain Location', 'Ubicación del dolor de oído', 'DK197' ],
[ 183, 'LocationOfPain', 'Pain Location', 'Ubicación del dolor', 'DK208' ],
[ 184, 'PhysicalAppearance', 'Physical Appearance', 'Apariencia física', 'DK199' ],
[ 185, 'Recurs', 'Recurs', 'Recurrentes', 'DK200' ],
[ 186, 'NailBedDiscoloration', 'Nail Bed Discoloration', 'Decoloración de la cama de uñas', 'DK204' ],
[ 187, 'NailDiscoloration', 'Nail Discoloration', 'Decoloración de las uñas', 'DK205' ],
[ 188, 'ToeNailInfection', 'Toenail Infection', 'Infección de uñas de los pies', 'DK206' ],
[ 189, 'NTC', 'Nausea Time Character', 'Carácter de tiempo de náusea', 'DK530' ],
[ 190, 'Cornea', 'Cornea', 'Córnea', 'DK428' ],
[ 191, 'NT', 'Nausea Triggers', 'Disparadores de náuseas', 'DK531' ],
[ 192, 'NRB', 'Nausea Relieved By', 'Náusea aliviada por', 'DK532' ],
[ 193, 'PainTiming', 'Time pattern of Pain', 'Patrón de tiempo del dolor', 'DK529' ],
[ 194, 'DK588', 'Eyelids Problem Location', 'Ubicación del problema de los párpados', 'DK588' ],
[ 195, 'Menstruating', 'Menstruating', 'Menstruando', 'DK210' ],
[ 196, 'FMentalDisorders', 'Mental Disorder', 'Trastorno mental', 'DK211' ],
[ 197, 'GlucoseFasting', 'Glucose, Fasting', 'Glucosa, ayuno', 'DK212' ],
[ 198, 'Bun', 'BUN', 'BOLLO', 'DK213' ],
[ 199, 'Creatinine', 'Creatinine', 'Creatinina', 'DK214' ],
[ 200, 'eGFR', 'eGFR', 'eGFR', 'DK215' ],
[ 201, 'Sodium', 'Sodium', 'Sodio', 'DK216' ],
[ 202, 'Potassium', 'Potassium', 'Potasio', 'DK217' ],
[ 203, 'Chloride', 'Chloride', 'Cloruro', 'DK218' ],
[ 204, 'CO2', 'CO2', 'CO2', 'DK219' ],
[ 205, 'AnionGap', 'Anion Gap', 'Anión gap', 'DK220' ],
[ 206, 'TotalProtein', 'Total Protein', 'Proteina total', 'DK221' ],
[ 207, 'Albumin', 'Albumin', 'Albúmina', 'DK222' ],
[ 208, 'TotalGlobulin', 'Total Globulin', 'Globulina Total', 'DK223' ],
[ 209, 'AGRatio', 'A/G Ratio', 'Ratio A / G', 'DK224' ],
[ 210, 'Calcium', 'Calcium', 'Calcio', 'DK225' ],
[ 211, 'AlkalinePhosphate', 'Alkaline Phosphate', 'Fosfato alcalino', 'DK226' ],
[ 212, 'ALT', 'ALT', 'ALT', 'DK227' ],
[ 213, 'AST', 'AST', 'AST', 'DK228' ],
[ 214, 'TotalBilirubin', 'Total Bilirubin', 'Bilirrubina total', 'DK229' ],
[ 215, 'Cpeptide', 'C-Peptide', 'Péptido C', 'DK230' ],
[ 216, 'UrineColor', 'Urine Color', 'Color de la orina', 'DK231' ],
[ 217, 'UrineGlucose', 'Glucose, Urine', 'Glucosa, orina', 'DK233' ],
[ 218, 'UrineBilirubin', 'Bilirubin, Urine', 'Bilirrubina, Orina', 'DK234' ],
[ 219, 'Ketones', 'Ketones, Urine', 'Cetonas, orina', 'DK235' ],
[ 220, 'UrineSpecficGravity', 'Urine Specific Gravity', 'Gravedad específica de la orina', 'DK236' ],
[ 221, 'BloodInUrine', 'Blood in Urine', 'Sangre en la orina', 'DK237' ],
[ 222, 'PHUrine', 'PH, Urine', 'PH, orina', 'DK238' ],
[ 223, 'ProteinUrine', 'Protein, Urine', 'Proteínas, Orina', 'DK239' ],
[ 224, 'UrineUrobilinogen', 'Urobilinogen, Urine', 'Urobilinógeno, Orina', 'DK240' ],
[ 225, 'NitriteUrine', 'Nitrite, Urine', 'Nitrito, orina', 'DK241' ],
[ 226, 'UrineLeukocyteEsterase', 'Leukocyte Esterase, Urine', 'Esterasa de leucocitos, orina', 'DK242' ],
[ 227, 'UrineWBC', 'WBC, Urine', 'WBC, orina', 'DK243' ],
[ 228, 'UrineRBC', 'RBC, Urine', 'RBC, orina', 'DK244' ],
[ 229, 'UrineBacteria', 'Bacteria, Urine', 'Bacterias, Orina', 'DK245' ],
[ 230, 'SquamousEpthelialUrine', 'Squamous Epithelial, Urine', 'Epitelio Escamoso, Orina', 'DK246' ],
[ 231, 'Cholsterol', 'Total Cholesterol', 'Colesterol total', 'DK247' ],
[ 232, 'HDLCholestrol', 'HDL Cholesterol', 'Colesterol HDL', 'DK248' ],
[ 233, 'Triglycerides', 'Triglycerides', 'Triglicéridos', 'DK249' ],
[ 234, 'LDLCholesterol', 'LDL Cholesterol', 'Colesterol LDL', 'DK250' ],
[ 235, 'LDLHDLRatio', 'LDL/HDL Ratio', 'Relación LDL / HDL', 'DK251' ],
[ 236, 'VLDLCholesterol', 'VLDL Cholesterol', 'Colesterol VLDL', 'DK253' ],
[ 237, 'TestosteroneFree', 'Testosterone, Free', 'Testosterona, Gratis', 'DK254' ],
[ 238, 'WBC', 'WBC', 'WBC', 'DK255' ],
[ 239, 'RBC', 'RBC', 'RBC', 'DK256' ],
[ 240, 'Hemoglobin', 'Hemoglobin', 'Hemoglobina', 'DK257' ],
[ 241, 'Hematocrit', 'Hematocrit', 'Hematocrito', 'DK258' ],
[ 242, 'MCV', 'MCV', 'MCV', 'DK259' ],
[ 243, 'MCH', 'MCH', 'MCH', 'DK260' ],
[ 244, 'MCHC', 'MCHC', 'MCHC', 'DK261' ],
[ 245, 'RDWCV', 'RDW-CV', 'RDW-CV', 'DK262' ],
[ 246, 'RDWSD', 'RDW-SD', 'RDW-SD', 'DK263' ],
[ 247, 'Platelets', 'Platelets', 'Plaquetas', 'DK264' ],
[ 248, 'MPV', 'MPV', 'MPV', 'DK265' ],
[ 249, 'NeutrophilsAbsolute', 'Neutrophils, Absolute', 'Neutrófilos Absolutos', 'DK266' ],
[ 250, 'LymphocytesAbsolute', 'Lymphocytes, Absolute', 'Linfocitos Absolutos', 'DK267' ],
[ 251, 'MonocytesAbsolute', 'Monocytes, Absolute', 'Monocitos Absolutos', 'DK268' ],
[ 252, 'Basophils', 'Basophils', 'Basófilos', 'DK269' ],
[ 253, 'Eosinophils', 'Eosinophils', 'Eosinófilos', 'DK270' ],
[ 254, 'Neutrophils', 'Neutrophils', 'Neutrofilos', 'DK271' ],
[ 255, 'Lymphocytes', 'Lymphocytes', 'Linfocitos', 'DK272' ],
[ 256, 'Monocytes', 'Monocytes', 'Monocitos', 'DK273' ],
[ 257, 'CK', 'CK', 'CK', 'DK274' ],
[ 258, 'TSH', 'TSH', 'TSH', 'DK275' ],
[ 259, 'EAG', 'eAG', 'eAG', 'DK276' ],
[ 260, 'HemoglobinA1C', 'Hemoglobin A1C', 'Hemoglobina a1c', 'DK277' ],
[ 261, 'UrineCalciumOxalate', 'Calcium Oxalate, Urine', 'Oxalato de calcio, orina', 'DK279' ],
[ 262, 'TestosteroneTotal', 'Testosterone, Total LCMSMS', 'Testosterona, LCMSMS Total', 'DK280' ],
[ 263, 'NTB', 'Nausea Time of Day', 'Náusea hora del día', 'DK533' ],
[ 264, 'VC', 'Vomiting Character', 'Personaje de vómito', 'DK534' ],
[ 265, 'VD', 'Vomit Description', 'Descripción del vómito', 'DK535' ],
[ 266, 'BreathingProblems', 'Breathing Problem', 'Problema respiratorio', 'DK301' ],
[ 267, 'AntiHEV', 'Anti-HEV IgM', 'Anti-HEV IgM', 'DK456' ],
[ 268, 'PPD', 'Purified Protein Derivate', 'Derivado de proteína purificada', 'DK457' ],
[ 269, 'ConcurrentIllness', 'Concurrent Illness', 'Enfermedad concurrente', 'DK281' ],
[ 270, 'VaginalLesion', 'Vaginal Lesion', 'Lesión vaginal', 'DK282' ],
[ 271, 'AnalDischarge', 'Rectal Discharge', 'Descarga rectal', 'DK283' ],
[ 272, 'Ophtalmoscopic', 'Ophthalmoscopic Exam', 'Examen oftalmoscópico', 'DK284' ],
[ 273, 'EyeAcuity', 'Eye Acuity', 'Agudeza ocular', 'DK285' ],
[ 274, 'CancerTreatment', 'Cancer Treatment', 'Tratamiento para el cáncer', 'DK286' ],
[ 275, 'UBT', 'Urea Breath Test', 'Prueba de aliento de urea', 'DK492' ],
[ 276, 'AbdominalCT', 'Abdominal CT', 'TC abdominal', 'DK431' ],
[ 277, 'AbdominalCTContrast', 'Abdominal CT Contrast', 'Contraste de TC abdominal', 'DK432' ],
[ 278, 'Glucose', 'Glucose', 'Glucosa', 'DK287' ],
[ 279, 'GramStain', 'Gram Stain', 'Tinción de Gram', 'DK288' ],
[ 280, 'UricAcid', 'S-Uric Acid', 'Ácido Súrico', 'DK289' ],
[ 281, 'FlankPain', 'Flank Pain', 'Dolor de costado', 'DK290' ],
[ 282, 'Nystagmus', 'Nystagmus', 'Nistagmo', 'DK291' ],
[ 283, 'Monospot', 'Monospot', 'Monospot', 'DK444' ],
[ 284, 'RapidStrep', 'Rapid Strep', 'Estreptococo rapido', 'DK445' ],
[ 285, 'HepA', 'Hep A Ab IgM', 'Hep A Ab IgM', 'DK446' ],
[ 286, 'HepB', 'Hep Bs Ag Screen', 'Pantalla Hep Bs Ag', 'DK447' ],
[ 287, 'HepC', 'Hep B Core Ab IgM', 'Hep B Core Ab IgM', 'DK448' ],
[ 288, 'HepD', 'Hep C Virus Ab', 'Virus de la hepatitis C Ab', 'DK449' ],
[ 289, 'AbdominalLocation', 'Abdominal Location', 'Localización Abdominal', 'DK433' ],
[ 290, 'GlucoseOGTT', 'OGTT', 'OGTT', 'DK342' ],
[ 291, 'ChestXrayResult', 'Chest X-ray Result', 'Resultado de la radiografía de tórax', 'DK292' ],
[ 292, 'AbdominalExam', 'Abdominal Exam', 'Examen abdominal', 'DK293' ],
[ 293, 'Paralysis', 'Paralysis', 'Parálisis', 'DK294' ],
[ 294, 'ShortnessOfBreath', 'Shortness of Breath', 'Falta de aliento', 'DK295' ],
[ 295, 'TeethDamage', 'Teeth Damage', 'Daños en los dientes', 'DK296' ],
[ 296, 'EyePressure', 'Eye Pressure', 'Presión ocular', 'DK297' ],
[ 297, 'PelvicUltrasound', 'Pelvic Ultrasound', 'Ultrasonido pelvico', 'DK304' ],
[ 298, 'ThyroidPalpation', 'Thyroid Palpation', 'Palpación tiroidea', 'DK303' ],
[ 299, 'NegativeBody', 'Negative Body Image', 'Imagen corporal negativa', 'DK337' ],
[ 300, 'RandomGlucose', 'Random Glucose', 'Glucosa al azar', 'DK343' ],
[ 301, 'DHManeuvar', 'Dix-Hallpike Maneuver', 'Maniobra de Dix-Hallpike', 'DK298' ],
[ 302, 'Abuse', 'Abuse', 'Abuso', 'DK299' ],
[ 303, 'RashTrigger', 'Rash Trigger', 'Disparador de erupción', 'DK300' ],
[ 304, 'CWC', 'Chest Ct W Contrast', 'Cofre Ct W Contraste', 'DK520' ],
[ 305, 'CUS', 'Carotid Ultrasound', 'Ultrasonido carotídeo', 'DK521' ],
[ 306, 'CultureLocation', 'Culture Location', 'Ubicación de la cultura', 'DK491' ],
[ 307, 'Age', 'Age', 'Años', 'DK464' ],
[ 308, 'Conjuctiva', 'Conjunctiva/Sclera', 'Conjuntiva / Sclera', 'DK305' ],
[ 309, 'CTScan', 'CT Scan', 'Tomografía computarizada', 'DK306' ],
[ 310, 'Rheumatological', 'Rheumatological Markers', 'Marcadores reumatológicos', 'DK307' ],
[ 311, 'EnergyLevel', 'Energy Level', 'Nivel de energía', 'DK308' ],
[ 312, 'SociallyOutgoing', 'Socially Outgoing', 'Socialmente saliente', 'DK309' ],
[ 313, 'DifficultyMovements', 'Difficulty with Movements', 'Dificultad con los movimientos.', 'DK310' ],
[ 314, 'AbnormalSpeech', 'Abnormal Speech', 'Habla anormal', 'DK311' ],
[ 315, 'Depression', 'Depression', 'Depresión', 'DK312' ],
[ 316, 'Anxiety', 'Anxiety', 'Ansiedad', 'DK313' ],
[ 317, 'BNP', 'BNP', 'BNP', 'DK317' ],
[ 318, 'SeptalDefect', 'Septal Defect', 'Defecto septal', 'DK318' ],
[ 319, 'Bipolar', 'Bipolar', 'Bipolar', 'DK314' ],
[ 320, 'BipolarProblem', 'Bipolar Problem Size', 'Tamaño del problema bipolar', 'DK315' ],
[ 321, 'CompulsiveBehaviour', 'Obsessive-Compulsive Behavior', 'Comportamiento obsesivo-compulsivo', 'DK316' ],
[ 322, 'Pericardiam', 'Pericardium', 'Pericardio', 'DK319' ],
[ 323, 'EjectionFraction', 'Ejection Fraction Percentage', 'Porcentaje de fracción de eyección', 'DK320' ],
[ 324, 'ArousalBy', 'Arousal By', 'Excitación por', 'DK326' ],
[ 325, 'SkinTexture', 'Skin Texture', 'Textura de la piel', 'DK328' ],
[ 326, 'LastDiet', 'Last Diet', 'Ultima dieta', 'DK321' ],
[ 327, 'ImportanceWeight', 'Importance of Weight', 'Importancia del peso', 'DK322' ],
[ 328, 'ObFeelings', 'Obese Feelings', 'Sentimientos obesos', 'DK323' ],
[ 329, 'Hallucinations', 'Tactile Hallucinations', 'Alucinaciones táctiles', 'DK324' ],
[ 330, 'Delusions', 'Delusions', 'Ilusiones', 'DK325' ],
[ 331, 'Behavior', 'Behavior', 'Comportamiento', 'DK329' ],
[ 332, 'Alcohol', 'Alcohol', 'Alcohol', 'DK332' ],
[ 333, 'SkinConditions', 'Skin Condition', 'Condición de piel', 'DK327' ],
[ 334, 'LeftTonsilExudate', 'Left Tonsil Exudate', '', 'DK733' ],
[ 335, 'DryMucosa', 'Dry Mucosa', '', 'DK734' ],
[ 336, 'ProstateExam', 'Prostate Exam', 'Examen de próstata', 'DK330' ],
[ 337, 'RectalExam', 'Rectal Exam', 'Examen rectal', 'DK331' ],
[ 338, 'Accident', 'Accident/Impact', 'Accidente / Impacto', 'DK333' ],
[ 339, 'Fell', 'Fell from Height', 'Cayó de altura', 'DK334' ],
[ 340, 'Endoscopy', 'Endoscopy', 'Endoscopia', 'DK335' ],
[ 341, 'Discoloration', 'Discoloration', 'Descoloramiento', 'DK336' ],
[ 342, 'ESR', 'ESR', 'ESR', 'DK338' ],
[ 343, 'Dimer', 'Dimer', 'Dimer', 'DK339' ],
[ 344, 'BNP', 'BNP', 'BNP', 'DK340' ],
[ 345, 'CRP', 'CRP', 'CRP', 'DK341' ],
[ 346, 'SwellingLocation', 'Swelling Location', 'Lugar de hinchamiento', 'DK345' ],
[ 347, 'RChestPain', 'Radiating Chest Pain', 'Dolor radiante en el pecho', 'DK461' ],
[ 348, 'RecurrentInfections', 'Recurrent Infections', 'Infecciones recurrentes', 'DK424' ],
[ 349, 'SuicidalBehavior', 'Suicidal Behavior', 'Comportamiento suicida', 'DK425' ],
[ 350, 'CSFColor', 'CSF Color', 'Color CSF', 'DK426' ],
[ 351, 'NAAT', 'NAAT', 'NAAT', 'DK344' ],
[ 352, 'BUNRatio', 'BUN/Creatinine Ratio', 'Proporción BUN / Creatinina', 'DK373' ],
[ 353, 'Bdirect', 'Bilirubin, Direct', 'Bilirrubina, Directa', 'DK374' ],
[ 354, 'AlbuminUrine', 'Albumin, Urine', 'Albúmina, Orina', 'DK375' ],
[ 355, 'VitaminD25Hydroxy', '25-Hydroxy Vitamin D', '25-hidroxi vitamina d', 'DK376' ],
[ 356, 'CreatinineUr24hr', 'Creatinine, Urine, 24 hr.', 'Creatinina, Orina, 24 h.', 'DK377' ],
[ 357, 'LegTest', 'Straight Leg Raise Test', 'Prueba de elevación de la pierna recta', 'DK346' ],
[ 358, 'CordParalysis', 'Cord Paralysis', 'Parálisis del cordón', 'DK347' ],
[ 359, 'CervicalXRay', 'Cervical X-ray', 'Radiografia cervical', 'DK348' ],
[ 360, 'Ultrasound', 'Abdominal Ultrasound', 'Ultrasonido abdominal', 'DK349' ],
[ 361, 'RectalBleeding', 'Rectal Bleeding', 'Sangrado rectal', 'DK351' ],
[ 362, 'MedicalCare', 'Medical Care', 'Atención médica', 'DK352' ],
[ 363, 'Culture', 'Culture', 'Cultura', 'DK353' ],
[ 364, 'VitaminB12', 'Vitamin B12', 'Vitamina B12', 'DK378' ],
[ 365, 'FolateSerum', 'Folate, Serum', 'Folato, Suero', 'DK379' ],
[ 366, 'Magnesium', 'Magnesium', 'Magnesio', 'DK380' ],
[ 367, 'T4Free', 'Thyroxine (T4)', 'Tiroxina (t4)', 'DK381' ],
[ 368, 'T3Free', 'Triiodothyronine (T3)', 'Triyodotironina (T3)', 'DK382' ],
[ 369, 'EOS', 'Eosinophils (Eso)', 'Eosinófilos (eso)', 'DK383' ],
[ 370, 'BASO', 'Basophils (Baso)', 'Basófilos (baso)', 'DK384' ],
[ 371, 'ImmatureGranulocytes', 'Immature Granulocytes', 'Granulocitos inmaduros', 'DK385' ],
[ 372, 'ImmatureGrans', 'Immature Granulocytes', 'Granulocitos inmaduros', 'DK386' ],
[ 373, 'NRBC', 'NRBC', 'NRBC', 'DK387' ],
[ 374, 'FerritinSerum', 'Ferritin, Serum', 'Ferritina, Suero', 'DK388' ],
[ 375, 'TestosteroneSerum', 'Testosterone, Serum', 'Testosterona, suero', 'DK389' ],
[ 376, 'IronLevel', 'Iron Level', 'Nivel de hierro', 'DK354' ],
[ 377, 'TIBC', 'TIBC', 'TIBC', 'DK355' ],
[ 378, 'TSaturation', 'Transferrin Saturation', 'Saturación de transferrina', 'DK356' ],
[ 379, 'PTH', 'PTH', 'PTH', 'DK357' ],
[ 380, 'Ghormone', 'Growth Hormone', 'Hormona de crecimiento', 'DK358' ],
[ 381, 'Jobs', 'Classification', 'Clasificación', 'DK016' ],
[ 382, 'JobExposures', 'Exposure To', 'Exposición a', 'DK018' ],
[ 383, 'Immunization', 'Immunization', 'Inmunización', 'DK036' ],
[ 384, 'CoughFluids', 'Cough Fluids Description', 'Descripción de fluidos para la tos', 'DK042' ],
[ 385, 'PhysicalActivity', 'Physical Activity', 'Actividad física', 'DK359' ],
[ 386, 'MRIBrain', 'MRI Brain', 'Cerebro de resonancia magnética', 'DK365' ],
[ 387, 'CTHead', 'CT of Head/Brain', 'TC de cabeza / cerebro', 'DK366' ],
[ 388, 'CTSinus', 'CT of Sinus/Face', 'TC del seno / cara', 'DK367' ],
[ 389, 'CTOrbit', 'CT of Orbit', 'TC de la órbita', 'DK368' ],
[ 390, 'CTEar', 'CT of Ear/Temporal Bone', 'TC de oreja / hueso temporal', 'DK369' ],
[ 391, 'RBacteria', 'Resistant Bacteria', 'Bacterias resistentes', 'DK360' ],
[ 392, 'TBiopsy', 'Tissue Biopsy', 'Biopsia de tejido', 'DK361' ],
[ 393, 'HTrauma', 'History of Trauma', 'Historia del trauma', 'DK362' ],
[ 394, 'CDefect', 'Congenital Defect', 'Defecto congenito', 'DK363' ],
[ 395, 'WoundHealing', 'Wound Healing', 'Cicatrización de la herida', 'DK364' ],
[ 396, 'MRIOrbit', 'MRI of Orbit', 'Resonancia magnética de la órbita', 'DK370' ],
[ 397, 'HILocation', 'Head Location', 'Ubicación de la cabeza', 'DK371' ],
[ 398, 'BartholinGland', 'Bartholin Gland', 'Glándula de bartholin', 'DK372' ],
[ 399, 'PMentalDisorders', 'Mental Disorders', 'Desordenes mentales', 'DK390' ],
[ 400, 'FaceNumbness', 'Facial Distribution of Pain/Numbness', 'Distribución facial del dolor / entumecimiento', 'DK391' ],
[ 401, 'IVAccess', 'IV Access', 'IV Acceso', 'DK393' ],
[ 402, 'Phosphate', 'Phosphate', 'Fosfato', 'DK394' ],
[ 403, 'SuicideResults', 'Columbia-Suicide Severity Results', 'Resultados de gravedad de suicidio de Colombia', 'DK392' ],
[ 404, 'KidneyBiopsy', 'Kidney Biopsy', 'Biopsia de riñón', 'DK395' ],
[ 405, 'IgG', 'Mycoplasma Pneumoniae - IgG', 'Mycoplasma Pneumoniae - IgG', 'DK396' ],
[ 406, 'IgM', 'Mycoplasma Pneumoniae - IgM', 'Mycoplasma Pneumoniae - IgM', 'DK397' ],
[ 407, 'AgglutininTiter', 'Cold Agglutinin Titer', 'Título de aglutinina fría', 'DK398' ],
[ 408, 'ArteriesStenosis', 'Significant Coronary Arteries Stenosis', 'Arteria coronaria significativa estenosis', 'DK399' ],
[ 409, 'LeftVentricle', 'Left Ventricle', 'Ventrículo izquierdo', 'DK400' ],
[ 410, 'MotorDevelopment', 'Child Motor Development', 'Desarrollo motor infantil', 'DK401' ],
[ 411, 'StomachpH', 'Stomach pH', 'PH del estómago', 'DK427' ],
[ 412, 'Overdose', 'Overdose', 'Sobredosis', 'DK402' ],
[ 413, 'Intoxicated', 'Currently Intoxicated', 'Actualmente intoxicado', 'DK403' ],
[ 414, 'Bite', 'Bite By', 'Mordida por', 'DK404' ],
[ 415, 'VoiceDescription', 'Voice Description', 'Descripción de la voz', 'DK405' ],
[ 416, 'IrisSpot', 'Iris Spot', 'Iris Spot', 'DK406' ],
[ 417, 'BreathingPatterns', 'Breathing Patterns', 'Patrones de respiración', 'DK407' ],
[ 418, 'GeneralAppearance', 'General Appearance', 'Apariencia general', 'DK408' ],
[ 419, 'IllnessExtenalService', 'ICD-10 Illness Codes', 'Códigos de enfermedad de la CIE-10', 'DK409' ],
[ 420, 'Gait', 'Gait', 'Paso', 'DK410' ],
[ 421, 'pKINR', 'INR', 'INR', 'DK412' ],
[ 422, 'PeriodsAge', 'Age', 'Años', 'DK422' ],
[ 423, 'PeriodsFrequency', 'Frequency', 'Frecuencia', 'DK423' ],
[ 424, 'PreviousTrauma', 'Previous Trauma', 'Trauma Anterior', 'DK413' ],
[ 425, 'SpecificSport', 'Specific Sport', 'Deporte especifico', 'DK414' ],
[ 426, 'HallucinationSleep', 'Hallucinations', 'Alucinaciones', 'DK415' ],
[ 427, 'BabyDiet', 'Baby Diet', 'Dieta del bebe', 'DK416' ],
[ 428, 'FamilyStructure', 'Family Structure', 'Estructura familiar', 'DK417' ],
[ 429, 'JawPain', 'Jaw Pain', 'Dolor de mandibula', 'DK418' ],
[ 430, 'PhysicallyActive', 'Physically Active', 'Físicamente activo', 'DK419' ],
[ 431, 'SleepingPatterns', 'Sleeping Patterns', 'Patrones de sueño', 'DK420' ],
[ 432, 'PapSmear', 'Pap Smear', 'Prueba de Papanicolaou', 'DK438' ],
[ 433, 'EyeMovements', 'Eye Movements', 'Movimientos oculares', 'DK439' ],
[ 434, 'RecentMedialCare', 'Recent Medical Care', 'Atención médica', 'DK440' ],
[ 435, 'Arthroconidium', 'Arthroconidium', 'Arthroconidium', 'DK441' ],
[ 436, 'Cfixation', 'Complement Fixation (CF)', 'Fijación Complementaria (CF)', 'DK442' ],
[ 437, 'Mif', 'Microimmunofluorescence Antibody Test (MIF)', 'Prueba de anticuerpos de microinmunofluorescencia (MIF)', 'DK443' ],
[ 438, 'Funduscopic Exam', 'Fundoycopic', 'Fundoycopic', 'DK480' ],
[ 439, 'Tomography', 'Tomography', 'Tomografía', 'DK481' ],
[ 440, 'Ulcers', 'Ulcers', '', 'DK735' ],
[ 441, 'Hyperactive', 'Hyperactive', '', 'DK594' ],
[ 442, 'Hypoactive', 'Hypoactive', '', 'DK595' ],
[ 443, 'ArterialpH', 'Arterial pH', 'Arterial pH', 'DK434' ],
[ 444, 'ArterialpCo2', 'Arterial pCo2', 'Arterial pCo2', 'DK435' ],
[ 445, 'ArterialpO2', 'Arterial pO2', 'Arterial pO2', 'DK436' ],
[ 446, 'ArterialHco3', 'Arterial Hco3 (bicarb)', 'Arterial Hco3 (bicarb)', 'DK437' ],
[ 447, 'Nontreponemal', 'Nontreponemal', 'No treponémico', 'DK450' ],
[ 448, 'Treponemal', 'Treponemal Tests', 'Pruebas treponémicas', 'DK451' ],
[ 449, 'Mumps', 'Mumps IgM Antibody', 'Anticuerpo IgM De Paperas', 'DK452' ],
[ 450, 'GastrinLevels', 'Gastrin Levels', 'Niveles de gastrina', 'DK453' ],
[ 451, 'Lens', 'Lens', 'Lente', 'DK454' ],
[ 452, 'AntiHDV', 'Anti-HDV IgM', 'Anti-HDV IgM', 'DK455' ],
[ 453, 'S-?HCG', 'S-HCG', 'S-HCG', 'DK429' ],
[ 454, 'Timebucket', 'Timebucket', 'Timebucket', 'DK430' ],
[ 455, 'PCR', 'PCR - Viral', 'PCR - Viral', 'DK462' ],
[ 456, 'Mammogram', 'Mammogram', 'Mamograma', 'DK463' ],
[ 457, 'Afrequency', 'Frequency', 'Frecuencia', 'DK465' ],
[ 458, 'Pulmonary', 'Pulmonary Function', 'Función pulmonar', 'DK466' ],
[ 459, 'Dyspnea', 'Nocturnal Dyspnea', 'Disnea nocturna', 'DK467' ],
[ 460, 'NormalActivity', 'Activity', 'Actividad', 'DK468' ],
[ 461, 'Clarity', 'Clarity', 'Claridad', 'DK469' ],
[ 462, 'Color', 'Color', 'Color', 'DK470' ],
[ 463, 'Viscosity', 'Viscosity', 'Viscosidad', 'DK471' ],
[ 464, 'Canalysis', 'Crystal Analysis', 'Análisis de cristal', 'DK472' ],
[ 465, 'SWBC', 'Synovial WBC', 'WBC sinovial', 'DK473' ],
[ 466, 'Sbacteria', 'Synovial Bacteria', 'Bacterias sinoviales', 'DK474' ],
[ 467, 'KOH', 'KOH Prep', 'KOH Prep', 'DK475' ],
[ 468, 'LDH', 'LDH', 'LDH', 'DK476' ],
[ 469, 'LaticAcid', 'Latic Acid', 'Ácido Latic', 'DK477' ],
[ 470, 'CreatinineAlbumin', 'Albumin', 'Albúmina', 'DK478' ],
[ 471, 'TonsilsRemoved', 'Tonsils Removed', '', 'DK736' ],
[ 472, 'Bultrasound', 'Breast Ultrasound', 'Ultrasonido de mama', 'DK479' ],
[ 473, 'ViralLoad', 'Viral Load', 'La carga viral', 'DK495' ],
[ 474, 'RTMP', 'Reported Temperature', 'Temperatura reportada', 'DK496' ],
[ 475, 'HPD', 'Hair Problem Distribution', 'Distribución del problema del cabello', 'DK497' ],
[ 476, 'PWSUH', 'Problem With Skin Under Hair', 'Problema con la piel debajo del cabello', 'DK498' ],
[ 477, 'Ctiers', 'Coccidiomycosis Titers', 'Titulos de coccidiomicosis', 'DK499' ],
[ 478, 'Osmolarity', 'Urine Osmolarity', 'Osmolaridad de la orina', 'DK482' ],
[ 479, 'UrineSodium', 'UrineSodium', 'Orina de sodio', 'DK483' ],
[ 480, 'ExcretionSodium', 'Excretion Sodium', 'Excreción de sodio', 'DK484' ],
[ 481, 'UrineSediment', 'Urine Sediment', 'Sedimento de orina', 'DK485' ],
[ 482, 'MRIKnee', 'MRI Knee', 'Rodilla de resonancia magnética', 'DK486' ],
[ 483, 'Radiography', 'Radiography', 'Radiografía', 'DK489' ],
[ 484, 'Coagulation', 'Coagulation', 'Coagulación', 'DK487' ],
[ 485, 'EyeLidExam', 'Eye Lid Exam', 'Examen de la tapa del ojo', 'DK488' ],
[ 486, 'Mbiopsy', 'Myocardial Biopsy', 'Biopsia de miocardio', 'DK490' ],
[ 487, 'ELISA', 'ELISA', 'Elisa', 'DK493' ],
[ 488, 'AsthmaScreen', 'Asthma Screen', 'Prueba de asma', 'DK494' ],
[ 489, 'KneeExam', 'Knee Exam', 'Examen de rodilla', 'DK512' ],
[ 490, 'EPF', 'Extremity Plain Fim', 'Extremidad llanura fim', 'DK502' ],
[ 491, 'CTE', 'CT Extremity', 'CT Extremidad', 'DK503' ],
[ 492, 'EMRI', 'Extremity MRI', 'RM de extremidades', 'DK504' ],
[ 493, 'EUS', 'Extremity Ultra Sound', 'Extremidad Ultra Sonido', 'DK505' ],
[ 494, 'Elocation', 'Extremity Location', 'Ubicación de la extremidad', 'DK506' ],
[ 495, 'SPF', 'Spinal Plain Film', 'Película llana espinal', 'DK507' ],
[ 496, 'SCT', 'Spinal CT', 'TC espinal', 'DK508' ],
[ 497, 'SMRI', 'Spinal MRI', 'Resonancia magnética espinal', 'DK509' ],
[ 498, 'SMC', 'Spinal MRI w Contrast', 'RM de la columna vertebral con contraste', 'DK510' ],
[ 499, 'Slocation', 'Spinal Location', 'Ubicación espinal', 'DK511' ],
[ 500, 'BloodSmear', 'Blood Smear', 'Frotis de sangre', 'DK500' ],
[ 501, 'WeakPulse', 'Weak Pulse', 'Pulso débil', 'DK501' ],
[ 502, 'BMS', 'Back Muscle Spasm', 'Espasmo muscular de la espalda', 'DK519' ],
[ 503, 'HBSA', 'Hepatitis B Surface Antibody', 'Anticuerpo de superficie contra la hepatitis B', 'DK513' ],
[ 504, 'RDP', 'Distribution Pattern', 'Patrón de distribución', 'DK514' ],
[ 505, 'RPS', 'Palm and Sole', 'Palma y suela', 'DK515' ],
[ 506, 'FOBT', 'Fecal Occult Blood Test', 'Prueba de sangre oculta en heces', 'DK516' ],
[ 507, 'TPA', 'Thyroid Peroxidase Antibody (TPO-Ab)', 'Anticuerpo de la peroxidasa tiroidea (TPO-Ab)', 'DK517' ],
[ 508, 'TUS', 'Thyroid Ultrasound', 'Ultrasonido de tiroides', 'DK518' ],
[ 509, 'PVU', 'Peripheral Vascular Ultrasound', 'Ultrasonido vascular periférico', 'DK522' ],
[ 510, 'RUS', 'Renal Ultrasound', 'Ultrasonido renal', 'DK523' ],
[ 511, 'RDU', 'Renal Doppler Ultrasound', 'Ultrasonido Doppler Renal', 'DK524' ],
[ 512, 'BLU', 'Bladder Ultrasound', 'Ultrasonido de vejiga', 'DK525' ],
[ 513, 'VCT', 'Voiding Cystourethrogram', 'Cistouretrograma de evacuación', 'DK526' ],
[ 514, 'Laparoscope', 'Laparoscope', 'Laparoscopio', 'DK527' ],
[ 515, 'VSSense', 'VS-Sense', 'VS-Sense', 'DK528' ],
[ 516, 'EEI', 'Erection/Ejaculation Issues', 'undefined', 'DK538' ],
[ 517, 'Swelling', 'Swelling', '', 'DK596' ],
[ 518, 'APA', 'Abdomen Pain Area', 'Área de dolor abdominal', 'DK536' ],
[ 519, 'LBPA', 'Lower Back Pain Area', 'Área de dolor de espalda baja', 'DK537' ],
[ 520, 'Yellow', 'Yellow', '', 'DK597' ],
[ 521, 'FMCO', 'FM-Constitutional', 'FM-Constitutional', 'DK542' ],
[ 522, 'FMR', 'FM-Respiratory', 'FM-Respiratory', 'DK543' ],
[ 523, 'FMENT', 'FM-ENT', 'FM-ENT', 'DK544' ],
[ 524, 'FMCA', 'FM-Cardiovascular', 'FM-Cardiovascular', 'DK545' ],
[ 525, 'FMNE', 'FM-Neurological', 'FM-Neurological', 'DK546' ],
[ 526, 'FMPS', 'FM-Psychiatric', 'FM-Psychiatric', 'DK547' ],
[ 527, 'FMLY', 'FM-Lymph', 'FM-Lymph', 'DK548' ],
[ 528, 'FMEY', 'FM-Eyes', 'FM-Eyes', 'DK549' ],
[ 529, 'FMGI', 'FM-GI', 'FM-GI', 'DK550' ],
[ 530, 'FMGU', 'FM-GU', 'FM-GU', 'DK551' ],
[ 531, 'FMMU', 'FM-Musculoskeletal', 'FM-Musculoskeletal', 'DK552' ],
[ 532, 'FMSK', 'FM-Skin', 'FM-Skin', 'DK553' ],
[ 533, 'FMEN', 'FM-Endocrine', 'FM-Endocrine', 'DK554' ],
[ 534, 'FMAL', 'FM-Allergy/Immun', 'FM-Allergy/Immun', 'DK555' ],
[ 535, 'LOQT', 'Congenital long QT syndrome', 'Síndrome de QT largo congénito', 'DK556' ],
[ 536, 'CLLQ', 'Close Living Quarters', 'Viviendas cercanas', 'DK557' ],
[ 537, 'DK589', 'Breasts Problem Location', 'Ubicación del problema de los senos', 'DK589' ],
[ 538, 'Normal', 'Normal', '', 'DK737' ],
[ 539, 'AnyLesion', 'Any Lesion', '', 'DK738' ],
[ 540, 'PapiledemaLeft', 'Papiledema Left', '', 'DK739' ],
[ 541, 'Normal', 'Normal', '', 'DK740' ],
[ 542, 'PapiledemaRight', 'Papiledema Right', '', 'DK741' ],
[ 543, 'Nohernia', 'No hernia', '', 'DK742' ],
[ 544, 'Normal', 'Normal', '', 'DK743' ],
[ 545, 'Fever', 'Patient Fever', 'Fiebre del paciente', 'DK558' ],
[ 546, 'Normal', 'Normal', '', 'DK744' ],
[ 547, 'Blue', 'Blue', '', 'DK745' ],
[ 548, 'ETM', 'Tympanic Membrane', 'undefined', 'DK539' ],
[ 549, 'EarCanal', 'Ear Canal', 'undefined', 'DK540' ],
[ 550, 'DifficultySwallow', 'Difficulty Swallowing', 'undefined', 'DK541' ],
[ 551, 'BruisingDescription', 'Bruising Description', 'undefined', 'DK695' ],
[ 552, 'IOS', 'Injury of Skin', 'Lesión de la piel.', 'DK565' ],
[ 553, 'VT', 'Visit Type', 'Tipo de visita', 'DK559' ],
[ 554, 'IT', 'Injury Type', 'Tipo de lesión', 'DK560' ],
[ 555, 'SI', 'Superficial Injury', 'Lesión superficial', 'DK561' ],
[ 556, 'OWT', 'Open Wound Type', 'Tipo de herida abierta', 'DK562' ],
[ 557, 'JI', 'Joint Injury', 'Lesión conjunta', 'DK563' ],
[ 558, 'SIT', 'Skin Injury Type', 'Tipo de lesión de piel', 'DK564' ],
[ 559, 'NewLocationOfPain', 'Pain Location', 'Ubicación del dolor', 'DK571' ],
[ 560, 'BurnPercentage', 'Burn Percentage', 'Porcentaje de quemaduras', 'DK148' ],
[ 561, 'Onset', 'Onset', 'Onset', 'DK566' ],
[ 562, 'Ldiseases', 'Lung Diseases', 'Enfermedades pulmonares', 'DK575' ],
[ 563, 'CHC', 'Hormonal Contraceptive', 'Hormonal Contraceptive', 'DK567' ],
[ 564, 'RHTI', 'Recent History of Throat Infection', 'Historia reciente de infecci�n de garganta', 'DK568' ],
[ 565, 'travel', 'Foreign Travel', 'undefined', 'DK569' ],
[ 566, 'ChestArea', 'Chest Area', 'undefined', 'DK573' ],
[ 567, 'IGGRT', 'IgM-IgG Rapid Test', 'IgM-IgG Rapid Test', 'DK570' ],
[ 568, 'EarSwellingLocation', 'Swelling Location', 'Lugar de hinchaz�n', 'DK574' ],
[ 569, 'Normal', 'Normal', '', 'DK746' ],
[ 570, 'Any', 'Any', '', 'DK747' ],
[ 571, 'NormalGait', 'Normal Gait', '', 'DK748' ],
[ 572, 'TestResult', 'Result', 'Resultado de la prueba', 'DK572' ],
[ 573, 'EyelidInfla', 'Eyelid Inflammation', 'Inflamación de los párpados', 'DK576' ],
[ 574, 'EyelidLoc', 'Eyelid Location', 'Ubicación del párpado', 'DK577' ],
[ 575, 'CTABrain', 'CTA Brain', 'CTA Brain', 'DK578' ],
[ 576, 'DK579', 'Inflammation', 'Inflamación', 'DK579' ],
[ 577, 'DK580', 'Joint Location', 'Ubicación conjunta', 'DK580' ],
[ 578, 'DK581', 'Pattern of Joint Pain', 'Patrón de dolor articular', 'DK581' ],
[ 579, 'DK582', 'Time pattern of Pain', 'Patrón de tiempo de dolor', 'DK582' ],
[ 580, 'DK583', 'Arthritis Analysis', 'Análisis de artritis', 'DK583' ],
[ 581, 'DK584', 'Aspiration', 'Aspiración', 'DK584' ],
[ 582, 'DK585', 'Change In Voice', 'Cambio en la voz', 'DK585' ],
[ 583, 'DK586', 'Joint Deformity Type', 'Tipo de deformaci�n articular', 'DK586' ],
[ 584, 'DK587', 'Rash Pain and Swelling', '', 'DK587' ],
[ 585, 'DK590', 'Exposure to Livestock', '', 'DK590' ],
[ 586, 'Any', 'Any', '', 'DK749' ],
[ 587, 'AsymmetricPeripheralPulses', 'Asymmetric Peripheral Pulses', '', 'DK750' ],
[ 588, 'RightFemoral', 'Right Femoral', '', 'DK751' ],
[ 589, 'LeftFemoral', 'Left Femoral', '', 'DK752' ],
[ 590, 'FemoralAssymetric', 'Femoral Assymetric', '', 'DK753' ],
[ 591, 'NormalFemoral', 'Normal Femoral', '', 'DK754' ],
[ 592, 'Normal', 'Normal', '', 'DK755' ],
[ 593, 'AnyHordeolumRight', 'Any Hordeolum Right', '', 'DK756' ],
[ 594, 'AnyHordeolumLeft', 'Any Hordeolum Left', '', 'DK757' ],
[ 595, 'Normal', 'Normal', '', 'DK758' ],
[ 596, 'NormalExam', 'Normal Exam', '', 'DK759' ],
[ 597, 'AnyDischarge', 'Any Discharge', '', 'DK760' ],
[ 598, 'NormalExam', 'Normal Exam', '', 'DK761' ],
[ 599, 'PulsatileMass', 'Pulsatile Mass', '', 'DK762' ],
[ 600, 'Normal', 'Normal', '', 'DK763' ],
[ 601, 'NoMass', 'No Mass', '', 'DK764' ],
[ 602, 'CVA-NoLeftTendernes', 'CVA - No Left Tendernes', '', 'DK765' ],
[ 603, 'CVA-NoRightTendernes', 'CVA - No Right Tendernes', '', 'DK766' ],
[ 604, 'Suprapubic-NoTendernes', 'Suprapubic-No Tendernes', '', 'DK767' ],
[ 605, 'NoHepato-Splenomegaly', 'No Hepato-Splenomegaly', '', 'DK768' ],
[ 606, 'MurphSignNegative', 'Murph Sign Negative', '', 'DK769' ],
[ 607, 'Normal', 'Normal', '', 'DK770' ],
[ 608, 'WarmandDry', 'Warm and Dry', '', 'DK771' ],
[ 609, 'NoWound', 'No Wound', '', 'DK772' ],
[ 610, 'AnyWound', 'Any Wound', '', 'DK773' ],
[ 611, 'AnyLesion', 'Any Lesion', '', 'DK774' ],
[ 612, 'NoSkinLesion', 'No Skin Lesion', '', 'DK775' ],
[ 613, 'NoRash', 'No Rash', '', 'DK776' ],
[ 614, 'LargeBruisedAreas', 'Large Bruised Areas', '', 'DK681' ],
[ 615, 'SmallBruisedAreas', 'Small Bruised Areas', '', 'DK682' ],
[ 616, 'Petheiae', 'Petheiae', '', 'DK683' ],
[ 617, 'Purpura', 'Purpura', '', 'DK684' ],
[ 618, 'BabinskiDescription', 'Babinski Description', 'undefined', 'DK793' ],
[ 619, 'GeneralPsyciatricObservationsDescription', 'General Psyciatric Observations Description', 'undefined', 'DK794' ],
[ 620, 'ThoughtsDescription', 'Thoughts Description', 'undefined', 'DK795' ],
[ 621, 'EmotionsDescription', 'Emotions Description', 'undefined', 'DK796' ],
[ 622, 'AbdomenSounds', 'AbdomenSounds', 'undefined', 'DK685' ],
[ 623, 'AbdominalPalpationDescription', 'Abdominal Palpation Description', 'undefined', 'DK696' ],
[ 624, 'AbdominalInspectionDescription', 'Abdominal Inspection Description', 'undefined', 'DK697' ],
[ 625, 'RespiratoryEffortDescription', 'Respiratory Effort Description', 'undefined', 'DK698' ],
[ 626, 'LymphaticExamDescription', 'Lymphatic Exam Description', 'undefined', 'DK699' ],
[ 627, 'EyeExamsDescription', 'Eye Exams Description', 'undefined', 'DK700' ],
[ 628, 'TemperatureandTextureDescription', 'Temperature and Texture Description', 'undefined', 'DK701' ],
[ 629, 'InjuryDescription', 'Injury Description', 'undefined', 'DK702' ],
[ 630, 'WoundDescription', 'Wound Description', 'undefined', 'DK703' ],
[ 631, 'SkinLesionsDescription', 'Skin Lesions Description', 'undefined', 'DK704' ],
[ 632, 'BenignSkinLesionDescription', 'Benign Skin Lesion Description', 'undefined', 'DK705' ],
[ 633, 'HairDescription', 'Hair Description', 'undefined', 'DK706' ],
[ 634, 'RashMorphologyDescription', 'Rash Morphology Description', 'undefined', 'DK707' ],
[ 635, 'RashTypeDescription', 'Rash Type Description', 'undefined', 'DK708' ],
[ 636, 'RashSpecificCharacteristicsDescription', 'Rash Specific Characteristics Description', 'undefined', 'DK709' ],
[ 637, 'RashDistributionDescription', 'Rash Distribution Description', 'undefined', 'DK710' ],
[ 638, 'RashShapeDescription', 'Rash Shape Description', 'undefined', 'DK711' ],
[ 639, 'RashArrangementDescription', 'Rash Arrangement Description', 'undefined', 'DK712' ],
[ 640, 'RashColorDescription', 'Rash Color Description', 'undefined', 'DK713' ],
[ 641, 'RashColorIntensityDescription', 'Rash Color Intensity Description', 'undefined', 'DK714' ],
[ 642, 'RashTextureDescription', 'Rash Texture Description', 'undefined', 'DK715' ],
[ 643, 'RightExternalEar-NormalExam', 'Right External Ear - Normal Exam', '', 'DK716' ],
[ 644, 'LeftExternalEar-NormalExam', 'Left External Ear - Normal Exam', '', 'DK717' ],
[ 645, 'DiminishedBreashSounds', 'Diminished Breash Sounds', '', 'DK718' ],
[ 646, 'PleuralRub', 'Pleural Rub', '', 'DK719' ],
[ 647, 'Rhythm-IrregularlyIrregular', 'Rhythm-Irregularly Irregular', '', 'DK720' ],
[ 648, 'ValsalvaManeuverMurmur', 'Valsalva Maneuver Murmur', '', 'DK721' ],
[ 649, 'CognitionDescription', 'Cognition Description', 'undefined', 'DK797' ],
[ 650, 'SuicideDescription', 'Suicide Description', 'undefined', 'DK798' ],
[ 651, 'NIIDescription', 'N II Description', 'undefined', 'DK799' ],
[ 652, 'BreastInspectionDescription', 'Breast Inspection Description', 'undefined', 'DK800' ],
[ 653, 'BreastPalpationDescription', 'Breast Palpation Description', 'undefined', 'DK801' ],
[ 654, 'CervicalSpineExamDescription', 'Cervical Spine Exam Description', 'undefined', 'DK802' ],
[ 655, 'ThoracicSpine/RibsExamDescription', 'Thoracic Spine/Ribs Exam Description', 'undefined', 'DK803' ],
[ 656, 'UpperExtermityExamDescription', 'Upper Extermity Exam Description', 'undefined', 'DK804' ],
[ 657, 'LowerExtremityExamDescription', 'Lower Extremity Exam Description', 'undefined', 'DK805' ],
[ 658, 'PeriorbitalEdemaDescription', 'Periorbital Edema Description', 'undefined', 'DK806' ],
[ 659, 'RightExternalEarDescription', 'Right External Ear Description', 'undefined', 'DK807' ],
[ 660, 'LeftExternalEarDescription', 'Left External Ear Description', 'undefined', 'DK808' ],
[ 661, 'ExternalNoseDescription', 'External Nose Description', 'undefined', 'DK809' ],
[ 662, 'HearingExamDescription', 'Hearing Exam Description', 'undefined', 'DK810' ],
[ 663, 'ParotidExamDescription', 'Parotid Exam Description', 'undefined', 'DK811' ],
[ 664, 'ChestPercussionDescription', 'Chest Percussion Description', 'undefined', 'DK812' ],
[ 665, 'ChestPalpationDescription', 'Chest Palpation Description', 'undefined', 'DK813' ],
[ 666, 'ExtremitiesDescription', 'Extremities Description', 'undefined', 'DK814' ],
[ 667, 'UrethralExamDescription', 'Urethral Exam Description', 'undefined', 'DK815' ],
[ 668, 'JugularVenousDistentionDescription', 'Jugular Venous Distention Description', 'undefined', 'DK816' ],
[ 669, 'HepatoJugularRefluxDescription', 'Hepato Jugular Reflux Description', 'undefined', 'DK817' ],
[ 670, 'FemaleExternalGenitaliaDescription', 'Female External Genitalia Description', 'undefined', 'DK818' ],
[ 671, 'Vaginal/CervixExamDescription', 'Vaginal/Cervix Exam Description', 'undefined', 'DK819' ],
[ 672, 'BimanualExamDescription', 'Bimanual Exam Description', 'undefined', 'DK820' ],
[ 673, 'ScrotalExamDescription', 'Scrotal Exam Description', 'undefined', 'DK821' ],
[ 674, 'PenisExamDescription', 'Penis Exam Description', 'undefined', 'DK822' ],
[ 675, 'BruisingExamDescription', 'Bruising Exam Description', 'undefined', 'DK777' ],
[ 676, 'LevelofconsciousnessDescription', 'Level of consciousness Description', 'undefined', 'DK778' ],
[ 677, 'PostureDescription', 'Posture Description', 'undefined', 'DK779' ],
[ 678, 'UpperExtremityStrengthDescription', 'Upper Extremity Strength Description', 'undefined', 'DK780' ],
[ 679, 'LowerExtremityStrenghtDescription', 'Lower Extremity Strenght Description', 'undefined', 'DK781' ],
[ 680, 'NIDescription', 'N I Description', 'undefined', 'DK782' ],
[ 681, 'NIII/IV/VIDescription', 'N III/IV/VI Description', 'undefined', 'DK783' ],
[ 682, 'NVDescription', 'N V Description', 'undefined', 'DK784' ],
[ 683, 'NVIIDescription', 'N VII Description', 'undefined', 'DK785' ],
[ 684, 'NVIIIDescription', 'N VIII Description', 'undefined', 'DK786' ],
[ 685, 'NIXDescription', 'N IX Description', 'undefined', 'DK787' ],
[ 686, 'NXDescription', 'N X Description', 'undefined', 'DK788' ],
[ 687, 'NXIDescription', 'N XI Description', 'undefined', 'DK789' ],
[ 688, 'NXIIDescription', 'N XII Description', 'undefined', 'DK790' ],
[ 689, 'SensoryExamDescription', 'Sensory Exam Description', 'undefined', 'DK791' ],
[ 690, 'DTRDescription', 'DTR Description', 'undefined', 'DK792' ]
]