# Generated by Django 3.1.5 on 2021-01-18 20:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessUserData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('criticality', models.IntegerField()),
                ('dfstatus', models.CharField(blank=True, max_length=300, null=True)),
                ('es_name', models.CharField(blank=True, max_length=300, null=True)),
                ('groups_complete', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('id_icd10_code', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('source', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('prevalence', models.IntegerField()),
                ('prior', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('version', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.symptom')),
                ('symptom_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.symptomgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('es_name', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.illnessuserdata')),
            ],
        ),
    ]
