# Generated by Django 3.1.5 on 2021-01-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0007_auto_20210126_1134'),
        ('illness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illnessdata',
            name='symptom_groups',
            field=models.ManyToManyField(blank=True, related_name='illness_symptomgroup', to='template.SymptomGroup'),
        ),
    ]
