# Generated by Django 3.1.5 on 2021-01-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0002_auto_20210124_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illnessdata',
            name='mergedVersions',
        ),
        migrations.AddField(
            model_name='illnessdata',
            name='mergedversions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
