# Generated by Django 3.1.5 on 2021-01-18 20:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentTypeRefDesc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('concept_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('cpt_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('default_value', models.BooleanField()),
                ('es_name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('short_name', models.CharField(blank=True, max_length=300, null=True)),
                ('long_name', models.CharField(blank=True, max_length=300, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('typedesc_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentTypeRefModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('es_name', models.CharField(blank=True, max_length=300, null=True)),
                ('tre_type', models.CharField(blank=True, max_length=300, null=True)),
                ('type_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_type_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatmenttyperefdesc')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('es_name', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatmenttyperefmodel')),
            ],
        ),
    ]
