# Generated by Django 3.1.5 on 2021-01-22 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('ingredient_rxcui', models.IntegerField(null=True)),
                ('ingredient_rxcui_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('rxcui', models.IntegerField(null=True)),
                ('added_by', models.CharField(blank=True, max_length=300, null=True)),
                ('tty', models.CharField(blank=True, max_length=300, null=True)),
                ('product_id', models.CharField(blank=True, max_length=300, null=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='NonDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=300, null=True)),
                ('long_name', models.CharField(blank=True, max_length=300, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('type_desc_id', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('treatment_group', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('old_name', models.CharField(blank=True, max_length=300, null=True)),
                ('load', models.BooleanField(null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('non_drugs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('non_drugs_descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('drugs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('drugs_descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
            ],
        ),
    ]
