# Generated by Django 3.1.5 on 2021-02-03 00:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentTypeRefDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('cpt_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, null=True, size=None)),
                ('default_value', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, max_length=300, null=True)),
                ('long_name', models.CharField(blank=True, max_length=300, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('typedesc_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentTypeRefModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('tre_type', models.CharField(blank=True, max_length=300, null=True)),
                ('type_id', models.IntegerField()),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_type_desc', models.ManyToManyField(blank=True, related_name='treatmenttype_treatmenttypedesc', to='treatment.TreatmentTypeRefDesc')),
            ],
        ),
    ]
