# Generated by Django 3.1.5 on 2021-02-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmenttyperefmodel',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
