# Generated by Django 3.1.5 on 2021-02-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_auto_20210202_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmenttyperefmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatmenttyperefmodel',
            name='updated_at',
        ),
    ]
