# Generated by Django 3.1.5 on 2021-02-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20210202_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmenttyperefdesc',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatmenttyperefdesc',
            name='updated_at',
        ),
    ]
