# Generated by Django 3.1.5 on 2021-01-18 20:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalSymptopGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('group_lag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SnomedCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('concept_id', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('expression', models.CharField(blank=True, max_length=300, null=True)),
                ('list_valuecode', models.CharField(blank=True, max_length=300, null=True)),
                ('list_value', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiple_values', models.CharField(blank=True, max_length=300, null=True)),
                ('criticality', models.IntegerField()),
                ('treatable', models.BooleanField()),
                ('prior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('question', models.CharField(blank=True, max_length=300, null=True)),
                ('es_question', models.CharField(blank=True, max_length=300, null=True)),
                ('antithesis', models.FloatField()),
                ('sub_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('bodyparts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('pain_swelling_id', models.IntegerField()),
                ('display_order', models.IntegerField(default=0)),
                ('icd_r_odes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('display_ymptom', models.BooleanField()),
                ('kiosk_name', models.CharField(blank=True, max_length=300, null=True)),
                ('formal_name', models.CharField(blank=True, max_length=300, null=True)),
                ('med_necessary', models.BooleanField()),
                ('min_diag_criteria', models.BooleanField()),
                ('display_dr_app', models.BooleanField()),
                ('gender_group', models.CharField(blank=True, max_length=300, null=True)),
                ('cardinality', models.BooleanField()),
                ('logical_group_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('de_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('symptom_type', models.CharField(blank=True, max_length=300, null=True)),
                ('time_type', models.TimeField()),
                ('min_range', models.FloatField()),
                ('max_range', models.FloatField()),
                ('is_range', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('parent', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('bodypart_code', models.CharField(blank=True, max_length=300, null=True)),
                ('es_name', models.CharField(blank=True, max_length=300, null=True)),
                ('cascade_up', models.BooleanField()),
                ('cascade_down', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SymptomTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_id', models.CharField(blank=True, max_length=300, null=True)),
                ('criticality', models.IntegerField()),
                ('treatable', models.BooleanField()),
                ('multiple_values', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('time_type', models.CharField(blank=True, max_length=300, null=True)),
                ('question', models.CharField(blank=True, max_length=300, null=True)),
                ('icdrcode', models.CharField(blank=True, max_length=300, null=True)),
                ('es_question', models.CharField(blank=True, max_length=300, null=True)),
                ('es_question_bk', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('es_name', models.CharField(blank=True, max_length=300, null=True)),
                ('symptom_type', models.CharField(blank=True, max_length=300, null=True)),
                ('px_no_normalized', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('prior', models.FloatField()),
                ('sub_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('datastore_templates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), size=None)),
                ('painswelling_id', models.IntegerField()),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bias', models.BooleanField()),
                ('descriptors', models.CharField(blank=True, max_length=300, null=True)),
                ('descriptor_file', models.CharField(blank=True, max_length=300, null=True)),
                ('scaletime_limit', models.IntegerField()),
                ('scaletime_limitstart', models.IntegerField()),
                ('timeunit_default', models.IntegerField()),
                ('scaleinfo_text', models.CharField(blank=True, max_length=300, null=True)),
                ('display_symptom', models.BooleanField()),
                ('kiosk_name', models.CharField(blank=True, max_length=300, null=True)),
                ('formal_name', models.CharField(blank=True, max_length=300, null=True)),
                ('definition', models.CharField(blank=True, max_length=300, null=True)),
                ('med_necessary', models.BooleanField()),
                ('displaydr_app', models.BooleanField()),
                ('active', models.BooleanField()),
                ('gender_group', models.CharField(blank=True, max_length=300, null=True)),
                ('cardinality', models.BooleanField()),
                ('antithesis', models.FloatField()),
                ('logical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.logicalsymptopgroup')),
                ('snomed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.snomedcode')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('symptom_count', models.BooleanField()),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('group_id', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.symptomcategory')),
            ],
        ),
        migrations.AddField(
            model_name='symptomcategory',
            name='symptom_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.symptomtemplate'),
        ),
    ]
