# Generated by Django 3.1.5 on 2021-01-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomgroup',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
