# Generated by Django 3.1.5 on 2021-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_symptomgroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='rows',
            field=models.ManyToManyField(blank=True, related_name='symptom_symptomdatastore', to='template.SymptomDataStore'),
        ),
    ]
