# Generated by Django 3.1.5 on 2021-01-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20210126_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptomtmpl',
            old_name='max_range',
            new_name='range_values',
        ),
        migrations.RemoveField(
            model_name='symptomtmpl',
            name='min_range',
        ),
        migrations.RemoveField(
            model_name='symptomtmpl',
            name='question',
        ),
        migrations.RemoveField(
            model_name='symptomtmpl',
            name='rangeValues',
        ),
        migrations.AlterField(
            model_name='datakeystore',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='datakeystore_valuestore', to='template.ValueStore'),
        ),
        migrations.AlterField(
            model_name='section',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='datakeystore_valuestore', to='template.SymptomCategory'),
        ),
        migrations.AlterField(
            model_name='symptomcategory',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='symptomcategory_symptom', to='template.Symptom'),
        ),
        migrations.AlterField(
            model_name='symptomgroup',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='symptomgroup_category', to='template.SymptomCategory'),
        ),
        migrations.AlterField(
            model_name='symptomgroup',
            name='datastore_ref_types',
            field=models.ManyToManyField(blank=True, related_name='symptomgroup_datakeystore', to='template.DataKeyStore'),
        ),
        migrations.AlterField(
            model_name='symptomgroup',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='symptomgroup_section', to='template.Section'),
        ),
    ]
