# Generated by Django 3.1.5 on 2021-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_auto_20210126_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomtmpl',
            name='prior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
