# Generated by Django 3.1.5 on 2021-01-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_auto_20210126_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='prior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
