# Generated by Django 3.1.5 on 2021-01-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0006_auto_20210126_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
