# Generated by Django 3.1.5 on 2021-01-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0007_auto_20210126_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomdatastore',
            name='modifier_values',
            field=models.ManyToManyField(blank=True, related_name='symptomdatastore_modifiertype', to='template.ModifierType'),
        ),
        migrations.AlterField(
            model_name='symptomdatastore',
            name='multiplier_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='symptomdatastore',
            name='source_info',
            field=models.ManyToManyField(blank=True, related_name='symptomdatastore_datastoresources', to='template.DataStoreSources'),
        ),
    ]
