# Generated by Django 3.1.5 on 2021-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0008_auto_20210126_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakeystore',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='datakeystore',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
